////
Copyright (c) 2025 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/).

SPDX-License-Identifier: CC-BY-4.0

////

////
TODO tc65:
- caluse 6.2.1
- clause 6.2.2
- clause 6.2.3
- explanation-access-rule-model chapter add infomration
////

= Access Rule Model (normative)

== General

The introduction in Chapter xref:introduction.adoc[] has explained in detail the background for AAS Security. 
The use of Identity Providers and Authentication Flows have been shown, which provide an access token to the client user application.
Such access token contains claims as subject attributes which can be used in the Access Rule Model as defined below.

In addition, the Access Rule Model contains further ABAC attributes like global attributes (also called environmental attributes) or object attributes.

<<image-access-rule-model>> gives an overview of the Access Rule Model.
Section <<bnf-grammar>> defines the text serialization of the Access Rule Model.
Section <<json-serialization>> defines the JSON schema of the Access Rule Model.

The Access Rule Model allows to define Access Rules in a modular way, so that parts can be reused.

* Attribute Groups can be defined to reuse combinations of attributes.
* Object Groups can be defined to reuse combinations of objects.
* Access Control Lists (ACLs) can be defined to reuse combinations of attributes and access rights.

Each Access Rule can define an own ACL or reuse an existing one.
Each Access Rule can provide access to single objects or object groups.
Each Access Rule can define an own Formula or reuse an existing one.

The formula decides, if an Access Rule becomes active or not.
Only if the overall result of the Formula is valid and true, the Access Rule becomes active.
A formula can include nested boolean expressions, comparisons and string operations.
A special operation match allows to work with tuples in lists, e.g. specificAssetId.

If access control is enabled for an AAS interface, access shall only be granted if there is (at least) one access control rule which permits the requested operation on the designated AAS object (<<objects>>).
If there is no rule the default behaviour is to deny access.


This grammar handles both respositories and registries. 
The symbol FieldIdentifier allows to use attributes of
AAS, Submodel, SubmodelElement, ConceptDescription, AAS-Descriptor and Submodel-Descriptor. 
Depending on the type of repository or registry such attributes are allowed or not.


The AAS Query Language and the AAS Access Rules share the same BNF grammar for formula expressions.
In addition to the text below, the further details of the formula expressions are explained in  link:https://industrialdigitaltwin.io/aas-specifications/IDTA-01002/v3.1/query-language.html[IDTA-01002, Query Language] .

Parts of the grammar for access control are reused from the query language described in link:https://industrialdigitaltwin.io/aas-specifications/IDTA-01002/v3.2[IDTA-01002]. Having a common grammar for access control rules and query language can be used by implementations to optimize queries on access restricted information. The grammar for AAS access control rules includes Conditions from the AAS query language as defined by link:https://industrialdigitaltwin.io/aas-specifications/IDTA-01002/v3.2/query-language.html[IDTA-01002, Query Language]. 

.Access Rule Model
[[image-access-rule-model]]
[plantuml,mage-access-rule-model,svg]
....
include::partial$diagrams/access-rule-model.puml[]
....

== Grammar for Access Rule Model

[[bnf-grammar]]
=== BNF grammar of Access Rules

The following BNF (Backus-Naur-Form) grammar defines the AAS Access Rule Model in a technology neutral form.
The grammar includes whitespaces, so that the examples in xref:annex/text-access-rule-examples.adoc[] can be validated.

The Security Model is explained step by step in the following Chapter <<explanation-access-rule-model>>.

Examples can be found in xref:annex/text-access-rule-examples.adoc[].

Further informative examples for RIGHTS, ROUTEs and HTTP requests can be found in xref:annex/route-examples.adoc[].

The BNF grammar artifacts are tested in the GitHub Actions CI/CD workflow "Validate spec artifacts".
This workflow runs the repository validation script `tools/validate_spec_artifacts.py`.
The script checks all BNF files for balanced delimiters, valid rule definitions and references to defined rules.
It also checks the BNF examples in the specification for balanced delimiters and validates model identifiers used in these examples against the related JSON Schema definitions.

link:https://bnfplayground.pauliankline.com/[BNF Playground] can be used for manual testing of the BNF grammar and examples.

The tested BNF is:

[source,bnf,linenums]
----
include::partial$bnf/access-rules.bnf[]
----

[[explanation-access-rule-model]]
=== Explanation of the Access Rule Model BNF

==== General

The AAS Access Rule Model can be used to describe access rules.
Whether and how access rules are enforced is beyond the specification of the model for access control.
The parties involved are supposed to agree on governance and policies.

The AAS Access Rule Model uses Attribute Based Access Control (ABAC), i.e. Attributes are used in access rules.
By ABAC also Role Based Access Control (RBAC) can be implemented by defining role attributes.
Subject Attributes and Roles may be provided as claims in Access Tokens.

Attributes in access rules are either claims from an Access Token provided by an Identity Provider, global attributes like actual DATETIME or from a Submodel like a property for a machine state.

Objects to be protected are either API Routes, Identifiables (e.g. AAS or Submodel), Referables (e.g. SubmodelElements), Descriptors or Fragments of all those (e.g. AssetId, SemanticId, SpecificAssetId).

==== Reuse

The AAS Access Rule Model allows to define modular parts which can be reused in different access rules.

These pre-defines can be referred to from other parts of the access control rules by the assigned <StringLiteral>. This allows to reuse commonly used definitions instead of having multiple copies spread over the access control rules. Table <<table-all-access-permission-rules>> summarizes the details for pre-definitions used in <AllAccessPermissionRules>.

[[table-all-access-permission-rules]]
.<AllAccessPermissionRules> pre-defines
[cols="1,3",options="header"]
|===
|Definition
|Description

|DEFATTRIBUTES
|Pre-defined <AttributeGroup>. Attributes can be combined into related groups, which may also be used in other groups. The group can be referenced using <UseAttributeGroup>.

|DEFOBJECTS
|Pre-defined <ObjectGroup>. Objects can be combined into related groups, which may also be used in other groups. The group can be referenced using <UseObjectGroup>.

|DEFACLS
|Pre-defined <ACL>. An ACL defines which access rights are given for a certain combination of attributes. The ACL can be referenced using <UseACL>.

|DEFFORMULAS
|Pre-defined <Formula>. FORMULAs define a Boolean result to decide whether an access rule is applicable and can be referenced using <UseFormula>. FORMULAs allow only expressions with Boolean results, e.g. comparisons; arithmetic is currently not supported.
|===

==== Access Rule Model

[source,bnf,linenums]
----
include::partial$bnf/access-rule-model.bnf[]
----

An Access Rule Model defines a list of Access PermissionRules. 
<AccessPermissionRule> defines a single access control rule granting permissions on the designated AAS objects. Table <<table-access-permission-rule>> describes the details of <AccessPermissionRule>. 

[[table-access-permission-rule]]
.<AccessPermissionRule>
[cols="1,3",options="header"]
|===
|Section
|Description

|ACCESSRULE:
|Either specifies the access control list (<ACL>) or contains a reference to an access control list (<UseACL>) pre-defined using DEFACLS (@todo 6.2.4.1, Table <<table-all-access-permission-rules>>). Refer to @todo 6.2.4.3 for further information on access control lists.

|OBJECTS:
|Defines the set of AAS objects to which the access permission applies. The list contains individual objects and/or refers to object groups pre-defined using DEFOBJECTS (@todo 6.2.4.1, Table <<table-all-access-permission-rules>>). Refer to @todo 6.2.4.5 for further information on objects.

|FORMULA:
|Defines the formula to be evaluated to determine whether the access permission is in effect. If the formula evaluates to true the access permission shall be enforced. Refer to @todo 6.2.4.7 for further information on formulas.

|FILTER:
|Filters can be used to restrict the exposure of an AAS object (@todo 6.2.4.5) depending on the object values. Only values passing through the filter are returned to the AAS user application. Any AAS object with values that do not match the filter expression shall be removed from the list of returned objects.
EXAMPLE See @todo C.9.

|===

For reuse in multiple Access Rules it also contains lists of Attribute Groups <DEFATTRIBUTES>, Object Groups <DEFOBJECTS>, ACLs <DEFACLS> and Formulas <DEFFORMULAS>.
Such elements defined for reuse get a name.

One Access Rule must either directly define an ACL or reuse an existing ACL definition.

One access rule may directly list Single Objects or may reuse defined Object Groups.

One access rule may directly define a Formula or may reuse a Formula definition.

An access rule may optionally include <FILTER> or <FILTERLIST> to further restrict the returned objects.
Without a filter, access is granted to the complete object covered by the access rule.

A filter is represented by <SecurityQueryFilter>.
It combines a <FRAGMENT> with either a <CONDITION> or a reference to a pre-defined formula using <UseFormula>.
The <CONDITION> is a Boolean <logicalExpression> that defines whether the referenced fragment of the given object can be accessed.
<FILTER> contains one <SecurityQueryFilter>.
<FILTERLIST> contains a list of <SecurityQueryFilter> elements and can therefore define multiple fragment-level restrictions.

The <FRAGMENT> identifies which part of the accessed object has to be filtered.
The related <FragmentLiteral> defines the prefix of a <FieldIdentifier> to be filtered, e.g. "$aasdesc#specificAssetIds[]" defines that the specificAssetIds part shall be filtered.

==== ACL

[source,bnf,linenums]
----
include::partial$bnf/acl.bnf[]
----

An ACL (Access Control List) defines which access rights apply depending on a required set of attributes.

Table <<table-acl>> describes the details of <ACL>.

[[table-acl]]
.<ACL>
[cols="1,3",options="header"]
|===
|Section
|Description

|ATTRIBUTES:
| List of ABAC attributes that the access control list depends on. The list contains definitions for individual attributes or pre-defined attribute groups introduced with DEFATTRIBUTES (@todo 6.2.4.1, Table <<table-all-access-permission-rules>>). Refer to @todo 6.2.4.4 for further information on ABAC attributes.

|RIGHTS:
| Enumeration of access rights subject to this access control list. See 
<<table-rights-to-verbs>> for the description of the possible access rights. Table <<table-rights-to-verbs>> defines how the rights apply to the interface operations defined in IEC 63278-5 and describes the semantics of the individual rights.

|ACCESS:
|Type of access managed by this access control list. See Table <<table-access>> for the description of possible access types.

|===

[[table-access]]
.<Access>
[cols="1,3",options="header"]
|===
|Access type enumeration
|Description

|`"ALLOW"`
| The respective permission is granted if the associated formula evaluates to true (@todo 6.2.4.7)

|`"DISABLED"`
| This access control list shall not be evaluated and is ignored. This can be used for test purposes.

|===

Attributes can be provided as a list of <SingleAttribute> elements and/or as references to pre-defined attribute groups using <UseAttributeGroup>.

The rights in ACLs essentially use the CRUDX pattern, i.e. rights for CREATE, READ, UPDATE, DELETE and EXECUTE can be defined.

Without an ALLOW rule any access is forbidden by default.
For testing and alternative configuration purposes, an access rule may be DISABLED.
To avoid complex conflicting situations, deny rules are not supported.

In addition, VIEW allows to see the existence of an element as Id or idShort, but not to read its values and its further attributes.

ALL is an abbreviation to define all rights.

===== Rights and operation verbs

The RIGHTS values are technology-neutral permissions. For HTTP/REST APIs these permissions are typically enforced on interface operations and their mapped HTTP methods.
The mapping in <<table-rights-to-verbs>> is intended to improve interoperability when ROUTE objects are used for authorization decisions.
Concrete informative examples for RIGHTS, ROUTEs and HTTP requests are given in xref:annex/route-examples.adoc[].

The normative operation-level mapping for the AAS HTTP/REST API (per-operation RIGHT and ROUTE) is defined in IDTA-01002 § "Operation to RIGHT Mapping" (annex). Implementations of this specification MUST follow that mapping when evaluating access rules against concrete HTTP operations.

[[table-rights-to-verbs]]
.Indicative mapping of RIGHTS to AAS operation verbs and HTTP methods
[cols="1,2,2,4",options="header"]
|===
|Right
|Operation verb
|HTTP method
|Meaning

|CREATE
|Post
|POST
|Permission to create a new resource at a collection or factory-style endpoint.

|CREATE
|Put
|PUT
|Permission to create a new resource at a client-addressable resource endpoint if the addressed resource does not yet exist.

|READ
|Get, GetAll
|GET
|Permission to read resource content.

|UPDATE
|Patch
|PATCH
|Permission to partially update an existing resource.

|UPDATE
|Put
|PUT
|Permission to replace an existing resource at a client-addressable resource endpoint.

|DELETE
|Delete
|DELETE
|Permission to delete an existing resource.

|EXECUTE
|Invoke
|POST
|Permission to invoke an operation.

|VIEW
|GetAll
|GET
|Permission to see that a resource exists, typically as identifiers, references, idShort values, or descriptor entries without access to the full resource value.

|ALL
|n/a
|n/a
|Abbreviation for all eligible rights.
|===

The mapping is not intended to redefine AAS Part 2 operations.
It clarifies how the abstract RIGHT values are typically applied when an authorization decision is made for a concrete HTTP route.
The same HTTP method can therefore be used for different rights depending on the targeted interface operation and the representation that is returned.
For example, GET may correspond to READ for full content access or VIEW for reference-only or existence-only access.
Search-style read operations may also use POST in specific interfaces.
For endpoints with create-or-replace or upsert semantics, the required right depends on whether the addressed resource already exists.
For example, `PUT /api/v3/submodels/{submodelIdentifier}` requires CREATE if the addressed submodel does not yet exist and UPDATE if it already exists.
The same principle applies to endpoint-specific POST operations such as `POST /api/v3/lookup/shells/{aasIdentifier}` if the endpoint creates the addressed resource when absent and updates it when present.


==== Attributes

[source,bnf,linenums]
----
include::partial$bnf/attributes.bnf[]
----

Table <<table-attribute-types>> describes the available ABAC attribute types.

[[table-attribute-types]]
.<ClaimAttribute>, <GlobalAttribute> and <ReferenceAttribute>
[cols="1,3",options="header"]
|===
|Attribute enumeration
|Description

|`"CLAIM"`
|ABAC attribute of the subject/requestor provided as a claim in the access token to the AAS interface (@todo 6.2.3).

EXAMPLE See @todo C.3, @todo C.6

|`"GLOBAL"`
|Global/environment condition available to the AAS interface, e.g., time. 

|`"REFERENCE"`
|Reference to an attribute of any Referable @todo [IEC 63278-2] within the scope of the AAS accessed via the AAS interface.

|===

Single Attributes are either claims from an Access Token provided by an Identity Provider, global attributes like actual DATETIME or references to a model field, e.g. to a SubmodelElement property for a machine state.
A REFERENCE attribute addresses a field by identifier, independently of the object currently evaluated.
This is useful when a rule for one object needs state data from another model context, for example checking a machine state from an OperationalData Submodel while filtering maintenance documents in a different Submodel.

An Attribute Group defines a list of single attributes and/or a list of names of other attribute groups.

Table <<table-global-attributes>> gives the details for global attributes.

[[table-global-attributes]]
.<GlobalAttribute>
[cols="1,3",options="header"]
|===
|Global attribute enumeration
|Description

|`"LOCALNOW"`
|Local time of the AAS interface that shall be used when evaluating the access control rule. LOCALNOW shall be derived from a trustworthy time source.
LOCALNOW shall include the information required to map to a valid <TimeLiteral>.

NOTE This is not necessarily the local system time of the system evaluating the access control rule. The AAS Responsible decides what is used as local time by the AAS interface.

EXAMPLE An AAS Responsible for a company located in central Europe may set LOCALNOW to central European time (CET) even if the AAS is hosted in Atlantic daylight time (ADT).


|`"UTCNOW"`
|Coordinated Universal Time. UTCNOW shall be derived from a trustworthy time source. 
UTCNOW shall include the information required to map to a valid <TimeLiteral>.

|`"CLIENTNOW"`
|Time as perceived by the AAS user application. A trustworthy value for CLIENTNOW can be established as result of the authentication process (@todo 5.2.2.1, @todo 5.2.2.2) if sufficient information on the location of the subject is available. The actual value may then be provided as authenticated attribute of the access token (@todo 6.2.3).
CLIENTNOW shall include the information required to map to a valid <TimeLiteral>.

|`"ANONYMOUS"`
|Anonymous access, i.e., the request does not contain an access token. ANONYMOUS is intended to be used for access control rules permitting access to public information provided by the AAS.

EXAMPLE See @todo C.1 and @todo C.2.

|===

[[objects]]
==== Objects

[source,bnf,linenums]
----
include::partial$bnf/objects.bnf[]
----

AAS objects are objects constituting the data represented by the AAS or an endpoint for an AAS operation (<RouteObject>).

<SingleObject> (@todo Figure 9) describes the AAS element to which an access control rule applies (Table <<table-access-permission-rules>>). 

Objects to be protected are either API Routes, Identifiables (e.g. AAS or Submodel), Referables (e.g. SubmodelElements), Descriptors or Fragments of those (e.g. AssetId, SemanticId, SpecificAssetId). Table <<table-single-object>> explains the different options to refer to an AAS element.

[[table-single-object]]
.<SingleObject>
[cols="1,3",options="header"]
|===
|Object type enumeration
|Description

|"ROUTE"
|A route defines the endpoint address of an interface operation (@todo IEC 63278-5). This allows to define access control for requested interface operations, interface operation groups, or complete interfaces.

An URL path (IETF RFC 1738, 3.1) preceded by “/” can be used with AAS to specify routes. An asterisk (“*”) can be used at the end of a <RouteLiteral> to refer to interface operation groups or complete interfaces.

EXAMPLE See @todo C.10

|`"IDENTIFIABLE"`
|Reference to an Identifiable; text string as defined by @todo [IEC 63278-5]

|`"REFERABLE"`
|Reference to a Referable; text string as defined by @todo [IEC 63278-5]

|`"FRAGMENT"`
|Reference to a fragment; text string as defined by @todo[IEC 63278-5]

|`"DESCRIPTOR"`
|A descriptor object, e.g. an AssetAdministrationShellDescriptor or a Submodel Descriptor as defined by @todo [IEC 63278-5]

|===

Details on identifiers used by <IdentifiableObject>, <ReferableObject>, <FragmentObject>, and <DescriptorObject> are described in subclause <<identifiers>>. 

ROUTE defines the endpoint address of an interface operation.
This allows access control to be defined for single interface operations, groups of interface operations, or complete interfaces.

For AAS HTTP/REST APIs, a ROUTE literal shall use the URL path part only, i.e. the part of the endpoint address starting with "/".
The scheme, authority, query part and fragment identifier are not part of ROUTE matching.
The deployment-specific server base URL is therefore handled separately from the ROUTE literal.

ROUTE matching uses the following rules:

* A ROUTE literal starting with "/" and not ending with "*" matches one concrete path.
* The literal "*" matches all routes.
* A ROUTE literal ending with "*" matches all routes with the given prefix.

Examples are "/shells", "/shells/*" and "*".
For HTTP/REST APIs the examples in xref:annex/route-examples.adoc[] show how ROUTE literals can be combined with RIGHTS and concrete request examples from AAS Part 2.

An Object Group defines a list of single objects and/or a list of names of other object groups.

[[identifiers]]
==== Identifiers

References to attribute values (@todo 6.2.4.4) and objects (@todo 6.2.4.5) use instance and field identifiers.

Instances can be referred to by a specific identifier or a wildcard “*” to apply to all objects of the specified type. The syntax of the <StringLiteral> used to identify a specific instance shall be defined by the AAS responsible. IEC 61406 provides a specification for instance identifiers that can be used with AAS.

Table <<table-field-identifiers>> enumerates the available identifiers.

[[table-field-identifiers]]
.Field Identifiers
[cols="1,3",options="header"]
|===
|Field identifier
|Description

|`$aas#`
| Prefix for value of AAS attribute fields

|`$sm#`
| Prefix for value of Submodel attribute fields

|`$sme#`
| Prefix for value of SubmodelElement attribute fields

|`$cd#`
| Prefix for value of Concept Description attribute fields

|`$aasdesc#`
| Prefix for value of AAS descriptor attribute fields. AAS descriptors are the entries in AAS registries.

|`$smdesc#`
| Prefix for value of Submodel descriptor attribute fields. Submodel descriptors are the entries in Submodel registries.

|===

==== Formulas

[source,bnf,linenums]
----
include::partial$bnf/formulas.bnf[]
----

FORMULAs define a logical expression with a Boolean result when an Access Rule is enabled/disabled.
FORMULAs allow to express only expressions with Boolean results.
Arithmetic in FORMULAS is currently not supported.

Nested logical expressions create combinations of several logical expressions, where any, all or none of the expressions needs to be enabled: *<logicalNestedExpression>, <logicalOrExpression>, <logicalAndExpression>, <logicalNotExpression>*.

String Comparison Operations compare or match the first given argument (left argument) with the second given argument (right argument). *$eq, $ne, $gt, $lt, $ge, $le* make an alphabetic string comparison. $**starts-with, $ends-with, $contains and $regex** check, if the first given argument is part of the second argument or if the first argument matches with the given REGEX.

Numerical Comparison Operations compare the first given argument (left argument) with the second given argument (right argument).
Since AAS also supports XS Datatypes Hex, Bool, DateTime and Time, related comparisons are available accordingly.

For specific comparisons datatypes can be casted to the other datatypes.
If a FieldIdentifier is used directly in a typed comparison, it is implicitly interpreted as the comparison type.
This implicit conversion is tried for all values addressed by the FieldIdentifier.
Values that cannot be converted are ignored for this FieldIdentifier evaluation.
If no addressed value can be converted, the comparison evaluates to FALSE.

Specific operations exist to extract parts from DateTime, i.e. $dayOfWeek, $dayOfMonth, $month, $year.
This enables access rules related to week days or specific times in the year.

An important special operation is $match, which can be used with any element containing a list of elements, e.g. semanticId[], specificAssetId[], SubmodelElementList or SubmodelElementCollection.
The list element is written with [] to express, that $match shall check if a certain expression is true for at least one element in the list.
FILTER defines one fragment restriction for a returned object, while FILTERLIST defines several fragment restrictions with independent conditions.


[[json-serialization]]
== JSON Serialization of Access Rule Model

The AAS Access Rule model can also be defined as a JSON schema.
Since the related JSON schema shall also allow automatic code generation, specific constraints must be fulfilled by such JSON schema.
The use of "oneof" is limited and type information for objects must be available.

It shall also be possible to check a JSON with the JSON schema.

Examples can be found in xref:annex/json-access-rule-examples.adoc[].
The JSON Schema artifacts and all JSON examples included in the specification are tested in the GitHub Actions CI/CD workflow "Validate spec artifacts".
This workflow runs `tools/validate_spec_artifacts.py` with the Python `jsonschema` package.
The script checks the JSON Schema files as JSON Schema Draft 7, resolves their `$ref` references, runs schema smoke tests for selected definitions, and validates every JSON example from the specification against the common access-rule JSON Schema and the access-rule-model JSON Schema.

The following schema meets such constraints:

[source,json,linenums]
----
include::partial$json/aas-queries-and-access-rules-schema.json[]
----

=== Explanation of the Access Rule Model JSON schema

==== General

The AAS Access Rule Model can be used to describe access rules.
Whether and how access rules are enforced is beyond the specification of the model for access control.
The parties involved are supposed to agree on governance and policies.

==== Access Rule Model

The Access Rules BNF grammar is expressed in JSON schema syntax.
Please refer to the detailed step by step explanation of the grammar.

[source,json,linenums]
----
include::partial$json/access-rule-model.json[]
----

==== Formulas and logical expressions

A detailed step by step explanation follows below the JSON schema code.

[source,json,linenums]
----
include::partial$json/formulas-and-logical-expressions.json[]
----

The provided JSON schema includes a _modelStringPattern_ starting with a $, so that the syntax of model elements can be checked by the schema, e.g. $sm.idShort.

String, number and boolean are supported by JSON itself.
Specific JSON Schema definitions are provided for datatypes Hex, DateTime and Time: _hexLiteralPattern_, _dateTimeLiteralPattern_ and _timeLiteralPattern_.
The DateTime and Time definitions use explicit regular expressions based on the AAS core meta verification functions `MatchesXsDateTime` and `MatchesXsTime`.
These verification functions correspond to the XSD-based DateTime and Time data types defined by the IDTA 01001 Part 1 Metamodel xref:bibliography.adoc#bib1[[1\]], especially https://industrialdigitaltwin.io/aas-specifications/IDTA-01001/v3.1/spec-metamodel/datatypes.html[Primitive and Simple Data Types].
For the generated AAS core meta verification definitions, see https://aas-core-works.github.io/aas-core-meta/v3/MatchesXsDateTime.html[MatchesXsDateTime] and https://aas-core-works.github.io/aas-core-meta/v3/MatchesXsTime.html[MatchesXsTime].
They are based on the XML Schema `xs:dateTime` and `xs:time` lexical representations defined in https://www.w3.org/TR/xmlschema-2/#dateTime[] and https://www.w3.org/TR/xmlschema-2/#time[], and the ISO 8601 formats referenced by XML Schema in https://www.w3.org/TR/xmlschema-2/#isoformats[].
Accordingly, DateTime and Time literals include seconds, may include fractional seconds, and may include a timezone (`Z` or an offset from `-14:00` to `+14:00`).
The end-of-day notation `24:00:00` is allowed, with only zero fractional seconds.
The day, month and year ranges in the BNF and JSON Schema are lexical constraints only.
Special calendar cases, such as February 29 in non-leap years or the 31st day of a month with only 30 days, shall still be rejected.

If an incoming value is provided in an incomplete ISO-like form, it shall be completed before it is serialized as a DateTime or Time literal.
If a Time value has no timezone information, it shall be interpreted as UTC and serialized with `Z`.
For example, the Time value `12:00:00` shall be interpreted and serialized as `12:00:00Z`.

_Value_ is used for comparisons and _StringValue_ is used for the specific string operations.
For type safety and automatic code generation, each possible type is available as an own object:

* String values can be given by _$field_, $__strVal__, $__attribute__ oder $__strCast__.
* Numerical values can be given by $__numVal__ or $__numCast__.
* Hex values can be given by $__hexVal__ or $__hexCast__.
* Bool values can be given by _$boolean_ or $__boolCast__.
* DateTime values can be given by $__dateTimeVal__ or $__dateTimeCast__.
* Time values can be given by $__timeVal__ or $__timeCast__.

Casts convert values to the given type if possible.
DateTime casts use string operands; Time casts use string or DateTime operands.
Direct comparisons between two FieldIdentifier operands are not valid because the type of both fields would be implicit.
To compare two fields, at least one operand shall use an explicit cast, e.g. compare _$field_ to $__strCast__, $__numCast__, $__dateTimeCast__, or $__timeCast__.

Parts of DateTime values can be extracted as numbers:

* _$dayOfWeek_ extracts the day of week as number, starting with 0 for Sunday.
* _$dayOfMonth_, _$month_, _$year_ extract the related part as number.

Except for direct FieldIdentifier operands in typed comparisons, if a conversion or any other operation is invalid, the complete expression has to be treated as invalid.
An error message shall be generated and the result of the complete expression becomes FALSE, so that the access is not allowed and/or the filter is empty.

To allow the use of different types in operations, arrays are used for parameters. _comparisonItems_ is used for comparisons and _stringItems_ is used for specific string operations.

_logicalExpressions_ and _match_ can be recursively nested.

== Exchange of Access Rules

Business Partners may be interested to exchange Access Rules.

As the AAS is a central point for data access, there is the need to support fine-grained access control that supports multiple roles as well as separate access control policies for individual elements or submodels in the AAS.
Access Control is based on Identity Management and can only be successfully implemented in a secure environment.
For this document, the focus lies on the supported access control model.

When AAS content is passed from one partner to another, this is typically related to a change in the access control domain of the partners involved (supplier, integrator, operator), i.e. the scope of the validity of access control policies.

In addition to the AAS content itself, also the defined access permissions have to be transferred between the partners due to the following two reasons:

[arabic]
. Access permissions to information elements of an AAS MUST be established in each access control domain.
. One partner MUST be able to pass a suggestion which access permissions SHOULD be established for the asset that is described in the AAS.

ABAC is a very flexible approach, that also encompasses role-based access as a role can be considered as one attribute in this context.
Other attributes might be the time-of-day, the location of the asset, the originating address and others.

As explained as an example above, a robot manufacturer suggests that for the robot the following roles shall be defined: machine setter, operator and a maintenance role.
Note that the roles have to be expressed by means of attributes of the AAS representing the robot.
He also suggests permissions for these roles, e.g. an installer (integrator) does have write-access to the program of the robot, but an operator does not.

Providing such suggested access rules, makes the integration of the operator much easier.
The operator can copy and paste the access rules into his AAS implementation and only needs to make adjustments.

The above example motivates that the access permission rules need to be passed from one access control domain to the other.

The enforcement of Access Rules is implementation specific.

This specification defines the text serialization of access rules and the JSON schema serialization of access rules.
The support of both is optional and not mandatory.

The JSON schema serialization is recommended.

Such serialization provides the possibility to exchange access rules.
An implementation may even store such serialized access rules in submodel elements BLOB or FILE, so that these can be accessed by the API and can be protected by access rules itself.

== API Queries and Access Rules

link:https://industrialdigitaltwin.io/aas-specifications/IDTA-01002/v3.1/query-language.html#query-language[Version 3.1 of the AAS API] defines queries and uses the same grammar and same JSON schema to define queries.
The JSON schema serialization is used in the related API operations.

In addition, using the same concepts will be needed for large amounts of AAS data.
Querying such large amounts of data and protecting such data with Access Rules requires optimized access of data.
Database queries may combine the filter expression provided by the client query with the FOMULAs of the Access Rules on the server.
