////
Copyright (c) 2025 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/).

SPDX-License-Identifier: CC-BY-4.0

////

[[access-rule-model]]
= Access Rule Model

== General

The introduction in Chapter xref:introduction.adoc[Introduction] has explained in detail the background for AAS Security.
The use of Identity Providers and Authentication Flows have been shown, which provide an access token to the client user application. Such access token contains claims as subject attributes which can be used in the Access Rule Model as defined below. In addition, the Access Rule Model contains further ABAC attributes like global attributes (also called environmental attributes) or object attributes.

ABAC attributes assessed by the AAS interface shall originate from a trustworthy source.

Attributes derived from data represented by the AAS (e.g., value of a SubmodelElement) are assumed to be implicitly trusted by the AAS interface.

Global attributes shall originate from a trustworthy source and their authenticity shall be protected (e.g., using a trusted local clock, relying on a trusted time service).

Subject attributes need to be mapped to the subject in an authenticated way. This functionality must be provided by the PIP. The AAS interface relies on access tokens to convey subject attributes <<access-tokens>>.

<<image-access-rule-model,Access Rule Model>> gives an overview of the Access Rule Model.
Section <<bnf-grammar,BNF grammar of Access Rules>> defines the text serialization of the Access Rule Model.
Section <<json-serialization,JSON Serialization of Access Rule Model>> defines the JSON schema of the Access Rule Model.

The Access Rule Model allows to define Access Rules in a modular way, so that parts can be reused (see <<reusable-definitions>>).

Whether an Access Rule becomes active or not is decided by Formulas  <<formulas>>. Only if the overall result of the Formula is valid and true, the Access Rule becomes active. A formula can include nested boolean expressions, comparisons and string operations. A dedicated match operation allows to work with tuples in lists, e.g. specificAssetId.

Access SHALL only be granted if there is (at least) one access rule which allows the requested action on the designated AAS object (Route/Identifiable/Referable/Fragment/Descriptor; see <<objects>>). If there is no access rule, the default behavior shall be to deny access.

This grammar applies to both, respositories and registries.
The symbol FieldIdentifier allows to use attributes of AAS, Submodel, SubmodelElement, ConceptDescription, AAS-Descriptor and Submodel-Descriptor.  Depending on the type of repository or registry such attributes are allowed or not.

The AAS Query Language and the AAS Access Rules share the same BNF grammar for formula expressions.
In addition to the text below, the further details of the formula expressions are explained in  link:https://industrialdigitaltwin.io/aas-specifications/IDTA-01002/v3.1/query-language.html[IDTA-01002, Query Language] .

AAS implementations MAY decide, to which extent the access rule model is used.
The access rule model can be used as a guideline which shows, what a client application will expect.

If an AAS implementation allows the exchange of access rules, it SHOULD follow the specification of the access rule model.

AAS implementations MAY decide to support only a subset of the access rules. If an AAS implementation, e.g., only provides a READ profile, only such access rules for defining READ access are required. Access control MAY also be limited to specific subsystems, e.g., AAS repository, submodel repository, concept description repository, AAS registry or submodel registry.

AAS systems are supposed to deal with a large amount of AAS and AAS Submodels. To reach the needed performance and meet memory and storage constraints an AAS implementation MAY translated the access rules into a representation that meets the needs of the respective implementation as long as the behavior complies to the stated rules.

.Access Rule Model
[[image-access-rule-model]]
[plantuml,image-access-rule-model,svg]
....
include::partial$diagrams/access-rule-model.puml[]
....

[[access-tokens]]
== Access Tokens

The evaluation of access rules to determine access to the AAS relies on access tokens to convey subject attributes.
An access token is an authenticated set of claims about ABAC attributes that were mapped to the subject accessing the AAS. The access token is typically obtained using an Identity Provider. The access token is presented to the AAS along with the API request.

An AAS Data Server trusts one or several Identity Providers.
An Identity Provider MAY also give the possibility to federate identities to/from other Identity Providers.

Trust means, that for such Identity Provider(s) an AAS Data Server can verify the public key of the Identity Provider.
Such public key MAY be available directly as a key, by a public certificate or by a verifiable credential.

The policy of a dataspace SHALL define which access tokens are trusted by the AAS.

The policy of a dataspaces SHALL define the set of subject ABAC attributes that are used as claims to determine authorization.

Access tokens used for operations resulting in modification of information or disclosure of non-public information provided by the AAS shall use a state-of-the-art, cryptographically strong asymmetric signature scheme to authenticate the access token xref:requirements.adoc#use-of-cryptography[Use of Cryptography].

AAS Security uses signed JWT (JSON Web Token) bearer tokens as Access Tokens, as they are defined in RFC 7519.

The JWT is digitally signed according to RFC 7519 with the private key of the Identity Provider.
The public key used as trust anchor needs to be accessible by the AAS server, such that the JWT can be verified.

Other properties like the lifetime of the token or Proof-of-Possession (RFC 7800) properties SHOULD be determined based on the use case.
//@todo IEC has a more strict requirement here: The life-time of an access token shall be limited.

AAS Security only requires the standard claims of the RFC 9068 Chapter 2.2 Data Structure for the JWT, i.e “iss” (Issuer), “exp” (Expiration time), “aud” (Audience), “sub” (Subject), “client_id” (Client identifier), “iat” (Issued at), “jti” (JWT ID).

The  specific requirements on “iss”, “sub” and “aud” SHOULD be defined by the dataspace policy.
//@todo I'd rather put a SHALL there. Messing up subject semantics breaks the whole access control model.

All claims in an Access Token can be used in ABAC access rules as attributes and as described in the Access Rule Model below.

Access rules can also be defined for anonymous access, i.e. no Access Token exists. +
This is especially important for the Digital Product Passport to be able to scan the QRCODE according to IEC 61406 with a normal mobile phone camera.

Further definitions can be made by dataspaces. A specific dataspace MAY define the technology how to get an access token and MAY also define the attributes which can be used in the ABAC access rules. Examples are discussed in xref:introduction.adoc#identity-providers[Identity Providers], xref:introduction.adoc#authentication-flows[Authentication Flows].

This both assures interoperability and makes it possible to integrate new dataspaces in the future.

== Grammar for Access Rule Model

[[bnf-grammar]]
=== BNF grammar of Access Rules

The following BNF (Backus-Naur-Form) grammar defines the AAS Access Rule Model in a technology neutral form.
The grammar includes whitespaces, so that the examples in xref:annex/text-access-rule-examples.adoc[] can be validated.

The Security Model is explained step by step in <<explanation-access-rule-model,Explanation of the Access Rule Model>>.

Examples can be found in xref:annex/text-access-rule-examples.adoc[].

Further informative examples for RIGHTS, ROUTEs and HTTP requests can be found in xref:annex/route-examples.adoc[].

The BNF grammar artifacts are tested in the GitHub Actions CI/CD workflow "Validate spec artifacts".
This workflow runs the repository validation script `tools/validate_spec_artifacts.py`.
The script checks all BNF files for balanced delimiters, valid rule definitions and references to defined rules.
It also checks the BNF examples in the specification for balanced delimiters and validates model identifiers used in these examples against the related JSON Schema definitions.

link:https://bnfplayground.pauliankline.com/[BNF Playground] can be used for manual testing of the BNF grammar and examples.

The tested BNF is:

[source,bnf,linenums]
----
include::partial$bnf/access-rules.bnf[]
----

[[explanation-access-rule-model]]
=== Explanation of the Access Rule Model

==== General

The AAS Access Rule Model can be used to describe access rules.
Whether and how access rules are enforced is beyond the specification of the model for access control.
The parties involved are supposed to agree on governance and policies.

The AAS Access Rule Model uses Attribute Based Access Control (ABAC), i.e. Attributes are used in access rules.
By ABAC also Role Based Access Control (RBAC) can be implemented by defining role attributes.
Subject Attributes and Roles may be provided as claims in Access Tokens.

Attributes in access rules are either claims from an Access Token provided by an Identity Provider, global attributes like actual DATETIME or from a Submodel like a property for a machine state.

Objects to be protected are either API Routes, Identifiables (e.g. AAS or Submodel), Referables (e.g. SubmodelElements), Descriptors or Fragments of all those (e.g. AssetId, SemanticId, SpecificAssetId).


==== Access Rule Model

An Access Rule Model <AllAccessPermissionRules> defines a list of <<access-permission-rules,Access Permission Rules>>.

The access rule model <AllAccessPermissionRules> also contains lists of Attribute Groups <DEFATTRIBUTES>, Object Groups <DEFOBJECTS>, ACLs <DEFACLS> and Formulas <DEFFORMULAS>.
These pre-defines can be referred to from other parts of the access control rules by the assigned <StringLiteral>. This allows to reuse commonly used definitions instead of having multiple copies spread over the access control rules. See <<reusable-definitions>>.

.Railroad diagram for <AllAccessPermissionRules>
[[image-access-control-rules-model]]
image::access-control-rules-model.svg[width=642]

[[reusable-definitions]]
==== Reusable Definitions

The AAS Access Rule Model allows to define modular parts which can be reused in different access rules.

.Railroad diagram for reusable definitions
[[image-access-control-rules-definitions]]
image::access-control-rules-definitions.svg[width=642]

Table <<table-all-access-permission-rules>> summarizes the details for pre-definitions used in <AllAccessPermissionRules>.

[[table-all-access-permission-rules]]
.<AllAccessPermissionRules> pre-defines
[cols="1,3",options="header"]
|===
|Definition
|Description

|DEFATTRIBUTES
|Pre-defined <AttributeGroup>. Attributes can be combined into related groups, which may also be used in other groups. The group can be referenced using <UseAttributeGroup>.

|DEFOBJECTS
|Pre-defined <ObjectGroup>. Objects can be combined into related groups, which may also be used in other groups. The group can be referenced using <UseObjectGroup>.

|DEFACLS
|Pre-defined <ACL>. An ACL defines which access rights are given for a certain combination of attributes. The ACL can be referenced using <UseACL>.

|DEFFORMULAS
|Pre-defined formula. Formulas can be referenced using <UseFormula>. 
|===

EXAMPLE See xref:annex/text-access-rule-examples.adoc#example-reuse-acl-object-formula[Reuse of ACL, OBJECT and FORMULA].

[[access-permission-rules]]
==== Access Permission Rules

<AccessPermissionRule> defines a single access control rule granting permissions on the designated AAS objects.

.Railroad diagram for <AccessPermissionRule>
[[image-access-control-rules-access-permission-rule]]
image::access-control-rules-access-permission-rule.svg[width=642]

Table <<table-access-permission-rule>> describes the details of <AccessPermissionRule>.

[[table-access-permission-rule]]
.<AccessPermissionRule>
[cols="1,3",options="header"]
|===
|Section
|Description

|ACCESSRULE:
|Either specifies the access control list (<ACL>) or contains a reference to an access control list (<UseACL>) pre-defined using DEFACLS. Access control lists are described in <<acl,ACL>>.

|OBJECTS:
|Defines the set of AAS objects to which the access permission applies. The list contains individual objects and/or refers to object groups pre-defined using DEFOBJECTS. Objects are described in <<objects,AAS Objects>>.

|FORMULA:
|Defines the formula to be evaluated to determine whether the access permission is in effect. Predefined formulas can be referenced using <UseFormula>. Formulas allow only expressions with Boolean results, e.g., comparisons; arithmetic is currently not supported. If the formula evaluates to true the access permission shall be enforced. Formulas are described in <<formulas,Conditions and Formulas>>.

|FILTER: +
FILTERLIST:
|Filters can be used to restrict the exposure of an AAS object depending on the object values. Only values passing through the filter are returned to the AAS user application. Any AAS object with values that do not match the filter expression shall be removed from the list of returned objects. +
EXAMPLE See xref:annex/text-access-rule-examples.adoc#example-filter-statement[Example with FILTER statement].

|===

An access rule may optionally include <FILTER> or <FILTERLIST> to further restrict the returned objects.
Without a filter, access is granted to the complete object covered by the access rule.

A filter is represented by <SecurityQueryFilter>.
It combines a <FRAGMENT> with either a <CONDITION> or a reference to a pre-defined formula using <UseFormula>.
The <CONDITION> is a Boolean <logicalExpression> that defines whether the referenced fragment of the given object can be accessed.
<FILTER> contains one <SecurityQueryFilter>.
<FILTERLIST> contains a list of <SecurityQueryFilter> elements and can therefore define multiple fragment-level restrictions.

The <FRAGMENT> identifies which part of the accessed object has to be filtered.
The related <FragmentLiteral> defines the prefix of a <FieldIdentifier> to be filtered, e.g. "$aasdesc#specificAssetIds[]" defines that the specificAssetIds part shall be filtered.

For a filter addressing SubmodelElements (Fragment `$sme`), the filter condition SHALL be evaluated separately for each SubmodelElement identified by its ID. 

Visibility is applied recursively to the element hierarchy: a SubmodelElement SHALL be returned only if it and all its parent elements are visible.

[[acl]]
==== ACL

An ACL (Access Control List) defines which access rights apply depending on a required set of attributes.

.Railroad diagram for <ACL>
[[image-access-control-rules-acl]]
image::access-control-rules-acl.svg[width=642]

Table <<table-acl>> describes the details of <ACL>.

[[table-acl]]
.<ACL>
[cols="1,3",options="header"]
|===
|Section
|Description

|ATTRIBUTES:
| List of ABAC attributes that the access control list depends on. The list contains definitions for individual attributes or pre-defined attribute groups introduced with DEFATTRIBUTES. Attributes are described in <<attributes,Attributes>>.

|RIGHTS:
| Enumeration of access rights subject to this access control list. Table <<table-rights-to-verbs>> describes the possible access rights, their semantics, and how they apply to the interface operations defined by the AAS API xref:bibliography.adoc#bib2[[2\]].

|ACCESS:
|Type of access managed by this access control list. See Table <<table-access>> for the description of possible access types.

|===

[[table-access]]
.<Access>
[cols="1,3",options="header"]
|===
|Access type enumeration
|Description

|`"ALLOW"`
| The respective permission is granted if the associated formula evaluates to true (see <<formulas,Conditions and Formulas>>). Without an ALLOW rule any access is forbidden by default.

|`"DISABLED"`
| This access control list shall not be evaluated and is ignored. This can be used for test purposes.

|===

USEACL can be used to refer to a predefined ACL (see <<reusable-definitions,Reusable Definitions>>).

.Railroad diagram for <UseACL>
[[image-access-control-rules-acl-reference]]
image::access-control-rules-acl-reference.svg[width=642]

==== Rights and operation verbs

The RIGHTS values are technology-neutral permissions. For HTTP/REST APIs these permissions are typically enforced on interface operations and their mapped HTTP methods.
The mapping in Table <<table-rights-to-verbs>> is intended to improve interoperability when ROUTE objects are used for authorization decisions.
Concrete informative examples for RIGHTS, ROUTEs and HTTP requests are given in xref:annex/route-examples.adoc[].

The normative operation-level mapping for the AAS HTTP/REST API (per-operation RIGHT and ROUTE) is defined in IDTA-01002 § "Operation to RIGHT Mapping" (annex). Implementations of this specification MUST follow that mapping when evaluating access rules against concrete HTTP operations.

[[table-rights-to-verbs]]
.Indicative mapping of RIGHTS to AAS operation verbs and HTTP methods
[cols="1,2,2,4",options="header"]
|===
|Right
|Operation verb
|HTTP method
|Meaning

|CREATE
|Post
|POST
|Permission to create new <<objects,AAS objects>> where the parent object is the AAS object designated in the OBJECTS: section of the <<access-permission-rules,Access Permission Rule>> (Table <<table-access-permission-rule>>).

|CREATE
|Put
|PUT
|Permission to create new <<objects,AAS objects>> where the parent object is the AAS object designated in the OBJECTS: section of the <<access-permission-rules,Access Permission Rule>> (Table <<table-access-permission-rule>>).

|READ
|Get, GetAll
|GET
|Permission to perform read operations on the <<objects,AAS objects>> designated in the OBJECTS: section of the <<access-permission-rules,Access Permission Rule>> (Table <<table-access-permission-rule>>).

FILTER: can be used to filter the result data on a sub-object granularity from the object data returned by the Get/GetAll operation. 

EXAMPLE See xref:annex/text-access-rule-examples.adoc#example-filter-statement[Example with FILTER statement].

|UPDATE
|Patch
|PATCH
|Permission to perform update operations on existing the <<objects,AAS objects>> designated in the OBJECTS: section of the <<access-permission-rules,Access Permission Rule>> (Table <<table-access-permission-rule>>).

|UPDATE
|Put
|PUT
|Permission to replace an existing <<objects,AAS object>> designated in the OBJECTS: section of the <<access-permission-rules,Access Permission Rule>> (Table <<table-access-permission-rule>>).

|DELETE
|Delete
|DELETE
|Permission to perform delete operations on the <<objects,AAS objects>> designated in the OBJECTS: section of the <<access-permission-rules,Access Permission Rule>> (Table <<table-access-permission-rule>>).

|EXECUTE
|Invoke
|POST
|Permission to invoke an operation. 
// Permission to execute a SubmodelElement of type Operation. 

|VIEW
|GetAll
|GET
|View the existence of an <<objects,AAS object>> as ID or idShort. This does not include access to the value and any other attributes of the AAS element.

EXAMPLE It is allowed to see, that a specific Submodel is present, but this does not imply, that access to any information stored within the Submodel is granted. 

|ALL
|n/a
|n/a
|Permission for full access on the designated <<objects,AAS objects>>, i.e., shorthand for a combination of all eligible permissions.
|===

The mapping is not intended to redefine AAS Part 2 operations.

It clarifies how the abstract RIGHT values are typically applied when an authorization decision is made for a concrete HTTP route.
The same HTTP method can therefore be used for different rights depending on the targeted interface operation and the representation that is returned.
For example, GET may correspond to READ for full content access or VIEW for reference-only or existence-only access.
Search-style read operations may also use POST in specific interfaces. For endpoints with create-or-replace or upsert semantics, the required right depends on whether the addressed resource already exists.

For example, `PUT /api/v3/submodels/\{submodelIdentifier\}` requires CREATE if the addressed submodel does not yet exist and UPDATE if it already exists.
The same principle applies to endpoint-specific POST operations such as `POST /api/v3/lookup/shells/\{aasIdentifier\}` if the endpoint creates the addressed resource when absent and updates it when present.


[[attributes]]
==== Attributes

<SingleAttribute> describes an ABAC attribute which is to be used in an <<acl,ACL>> (Table <<table-acl>>).

.Railroad diagram for attributes
[[image-access-control-rules-attributes]]
image::access-control-rules-attributes.svg[width=642]

Table <<table-attribute-types>> describes the available ABAC attribute types.

[[table-attribute-types]]
.<ClaimAttribute>, <ClaimPathAttribute>, <GlobalAttribute> and <ReferenceAttribute>
[cols="1,3",options="header"]
|===
|Attribute enumeration
|Description

|`"CLAIM"`
|ABAC attribute of the subject/requestor provided as a top-level claim in the access token to the AAS interface (see xref:access-rule-model.adoc#access-tokens[Access token]). The <ClaimLiteral> identifies the top-level claim by its member name. When used without a cast as a <StringOperand>, the selected claim value shall be a JSON string.

EXAMPLE See xref:annex/text-access-rule-examples.adoc#example-authenticated-users[authenticated users] and xref:annex/text-access-rule-examples.adoc#example-business-partner-number[BusinessPartnerNumber].

|`"CLAIMPATH"`
|ABAC attribute selected from the verified JWT Claims Set with a non-empty JSON Pointer defined by https://www.rfc-editor.org/rfc/rfc6901.html[RFC 6901]. The text representation encodes the pointer as a JSON string; quotation mark, reverse solidus, and control characters use JSON escaping, while pointer separators are written as `/`. A <ClaimPathAttribute> can select any JSON value, including a nested scalar, object, or complete array; its value type is determined only after the pointer is resolved. It is not JSONPath and the URI-fragment form beginning with `#` shall not be used.

EXAMPLE `CLAIMPATH("/realm_access/roles")` selects the `roles` value in the nested `realm_access` object. See xref:annex/text-access-rule-examples.adoc#example-nested-claim-path[Nested and multi-valued access-token claims].

|`"GLOBAL"`
|Global/environment condition available to the AAS interface, e.g., time. 

|`"REFERENCE"`
|Reference to an attribute of any Referable as defined by the AAS metamodel xref:bibliography.adoc#bib1[[1\]] within the scope of the AAS accessed via the AAS interface.

|===

Single Attributes are either claims from an Access Token provided by an Identity Provider, global attributes like actual DATETIME or references to a model field, e.g. to a SubmodelElement property for a machine state.
An Attribute Group defines a list of single attributes and/or a list of names of other attribute groups.

A <ClaimAttribute> and a <ClaimPathAttribute> are selectors, not declarations of the runtime type of the selected JSON value. <ClaimAttribute> selects one top-level member by its member name. <ClaimPathAttribute> shall be evaluated against the root of the verified JWT Claims Set. JSON Pointer reference tokens shall be decoded and evaluated as specified by RFC 6901. In particular, `~1` represents `/`, `~0` represents `~`, object member names are compared without Unicode normalization, and array indices use zero-based decimal notation without leading zeros. A pointer containing an invalid escape, a pointer that does not resolve, the `-` array token, or a leading-zero token applied to an array does not resolve to an attribute value.

The ATTRIBUTES section declares the attributes that a formula may use; declaration alone does not require a claim to be present. An attribute is resolved when its occurrence is evaluated by the formula. If a <ClaimAttribute> or <ClaimPathAttribute> is absent, does not resolve, resolves to `null`, or has a JSON type that is not accepted by the consuming operation, that operation shall be indeterminate. The enclosing logical expression shall handle that result according to the three-valued logic defined in <<formulas>>.

Implementations shall make claims available to attribute evaluation only after all applicable access-token validation has succeeded. This includes cryptographic validation with an explicitly allowed algorithm and validation of the issuer, audience, temporal claims, and token type or purpose according to https://www.rfc-editor.org/rfc/rfc8725.html[RFC 8725] and the applicable access-token profile, such as https://www.rfc-editor.org/rfc/rfc9068.html[RFC 9068].

A REFERENCE attribute addresses a field by identifier, independently of the object currently evaluated.
This is useful when a rule for one object needs state data from another model context, for example checking a machine state from an OperationalData Submodel while filtering maintenance documents in a different Submodel.
EXAMPLE See xref:annex/text-access-rule-examples.adoc#example-reference-machine-state-filter[Reference Attribute and state-dependent filtering].

Table <<table-global-attributes>> gives the details for global attributes.

[[table-global-attributes]]
.<GlobalAttribute>
[cols="1,3",options="header"]
|===
|Global attribute enumeration
|Description

|`"LOCALNOW"`
|Local time of the AAS interface that shall be used when evaluating the access control rule. LOCALNOW shall be derived from a trustworthy time source.
LOCALNOW shall include the information required to map to a valid <TimeLiteral>.

NOTE This is not necessarily the local system time of the system evaluating the access control rule. The AAS Responsible decides what is used as local time by the AAS interface.

EXAMPLE An AAS Responsible for a company located in central Europe may set LOCALNOW to central European time (CET) even if the AAS is hosted in Atlantic daylight time (ADT).


|`"UTCNOW"`
|Coordinated Universal Time. UTCNOW shall be derived from a trustworthy time source. 
UTCNOW shall include the information required to map to a valid <TimeLiteral>.

|`"CLIENTNOW"`
|Time as perceived by the AAS user application. A trustworthy value for CLIENTNOW can be established as result of the authentication process (see xref:introduction.adoc#authentication-flows[Authentication Flows]) if sufficient information on the location of the subject is available. The actual value may then be provided as authenticated attribute of the access token (see xref:access-rule-model.adoc#access-tokens[Access token]).
CLIENTNOW shall include the information required to map to a valid <TimeLiteral>.

|`"ANONYMOUS"`
|Anonymous access, i.e., the request does not contain an access token. ANONYMOUS is intended to be used for access control rules permitting access to public information provided by the AAS.

EXAMPLE See xref:annex/text-access-rule-examples.adoc#example-anonymous-complete-api[complete API] and xref:annex/text-access-rule-examples.adoc#example-anonymous-semanticids[list of semanticIDs].

|===

<AttributeGroup> allows to define a set of attributes in a pre-defined group (see <<reusable-definitions,Reusable Definitions>>) that can be referenced by USEATTRIBUTES. Attribute groups may be recursive, i.e., an attribute group can be composed of attribute groups.

.Railroad diagram for <AttributeGroup> and <UseAttributeGroup>
[[image-access-control-rules-attribute-reference]]
image::access-control-rules-attribute-reference.svg[width=642]

In order to use attributes as operands the query language defined in link:https://industrialdigitaltwin.io/aas-specifications/IDTA-01002/v3.2/query-language.html[IDTA-01002, Query Language] is extended.

The capability to use attributes as operands in the evaluation of access control rules is an important concept of ABAC. At the time of evaluation, the operand will be substituted with the actual value of the attributed, e.g., as provided within a claim of the access token.

The required additions for <StringOperand> and <StringNonFieldOperand> are shown in the BNF grammar.

[[objects]]
==== AAS Objects

AAS objects are objects constituting the data represented by the AAS or an endpoint for an AAS operation (<RouteObject>).

<SingleObject> describes the AAS element to which an access control rule applies (see Table <<table-access-permission-rule>>).

Objects to be protected are either API Routes, Identifiables (e.g. AAS or Submodel), Referables (e.g. SubmodelElements), Descriptors or Fragments of those (e.g. AssetId, SemanticId, SpecificAssetId). Table <<table-single-object>> explains the different options to refer to an AAS element.

Details on identifiers used by <IdentifiableObject>, <ReferableObject>, <FragmentObject>, and <DescriptorObject> are described in <<identifiers,Identifiers>>.

.Railroad diagram for objects
[[image-access-control-rules-objects]]
image::access-control-rules-objects.svg[width=642]

[[table-single-object]]
.<SingleObject>
[cols="1,3",options="header"]
|===
|Object type enumeration
|Description

|"ROUTE"
|A route defines the endpoint address of an interface operation as defined by the AAS API xref:bibliography.adoc#bib2[[2\]]. This allows to define access control for requested interface operations, interface operation groups, or complete interfaces.

An URL path (IETF RFC 1738, 3.1) preceded by “/” can be used with AAS to specify routes. An asterisk (“*”) can be used at the end of a <RouteLiteral> to refer to interface operation groups or complete interfaces.

EXAMPLE See xref:annex/route-examples.adoc#example-requests-by-right[example requests by right].

|`"IDENTIFIABLE"`
|Reference to an Identifiable; text string as defined by the AAS API xref:bibliography.adoc#bib2[[2\]].

|`"REFERABLE"`
|Reference to a Referable; text string as defined by the AAS API xref:bibliography.adoc#bib2[[2\]].

|`"FRAGMENT"`
|Reference to a fragment; text string as defined by the AAS API xref:bibliography.adoc#bib2[[2\]].

|`"DESCRIPTOR"`
|A descriptor object, e.g. an AssetAdministrationShellDescriptor or a Submodel Descriptor as defined by the AAS API xref:bibliography.adoc#bib2[[2\]].

|===

Details on identifiers used by <IdentifiableObject>, <ReferableObject>, <FragmentObject>, and <DescriptorObject> are described in <<identifiers,Identifiers>>.

ROUTE defines the endpoint address of an interface operation.
This allows access control to be defined for single interface operations, groups of interface operations, or complete interfaces.

For AAS HTTP/REST APIs, a ROUTE literal shall use the URL path part only, i.e. the part of the endpoint address starting with "/".
The scheme, authority, query part and fragment identifier are not part of ROUTE matching.
The deployment-specific server base URL is therefore handled separately from the ROUTE literal.

ROUTE matching uses the following rules:

* A ROUTE literal starting with "/" and not ending with "*" matches one concrete path.
* The literal "*" matches all routes.
* A ROUTE literal ending with "*" matches all routes with the given prefix.

Examples are "/shells", "/shells/*" and "*".
For HTTP/REST APIs the examples in xref:annex/route-examples.adoc[] show how ROUTE literals can be combined with RIGHTS and concrete request examples from AAS Part 2.

<ObjectGroup> allows to combine a set of objects in pre-defined group (see <<reusable-definitions,Reusable Definitions>>) that can be referenced by USEOBJECTS. Object groups may be recursive, i.e., an object group can be composed of other object groups.

.Railroad diagram for <ObjectGroup> and <UseObjectGroup>
[[image-access-control-rules-object-reference]]
image::access-control-rules-object-reference.svg[width=642]

[[identifiers]]
==== Identifiers

References to attribute values (see <<attributes,Attributes>>) and objects (see <<objects,AAS Objects>>) use instance and field identifiers.

Instances can be referred to by a specific identifier or a wildcard “*” to apply to all objects of the specified type.
The syntax of the <StringLiteral> used to identify a specific instance shall be defined by the AAS Responsible according to the identifier policy described in xref:requirements.adoc#_identifier_management[Identifier management].

Table <<table-field-identifiers>> enumerates the available identifiers.

[[table-field-identifiers]]
.Field Identifiers
[cols="1,3",options="header"]
|===
|Field identifier
|Description

|`$aas#`
| Prefix for value of AAS attribute fields

|`$sm#`
| Prefix for value of Submodel attribute fields

|`$sme#`
| Prefix for value of SubmodelElement attribute fields

|`$cd#`
| Prefix for value of Concept Description attribute fields

|`$aasdesc#`
| Prefix for value of AAS descriptor attribute fields. AAS descriptors are the entries in AAS registries.

|`$smdesc#`
| Prefix for value of Submodel descriptor attribute fields. Submodel descriptors are the entries in Submodel registries.

|===

[[formulas]]
==== Conditions and Formulas

Any <LogicalExpression> described using the AAS query language defined by link:https://industrialdigitaltwin.io/aas-specifications/IDTA-01002/v3.2/query-language.html[IDTA-01002, Query Language] may be used in a formula for access control.

The logical expression used as condition shall evaluate to true, false, or indeterminate. If the expression evaluates to true the respective <<access-permission-rules,Access Permission Rule>> shall be enforced. A false or indeterminate result shall not grant access.

Arithmetic in Formulas is currently not supported.

Nested logical expressions create combinations of several logical expressions, where any, all or none of the expressions needs to be enabled: *<logicalNestedExpression>, <logicalOrExpression>, <logicalAndExpression>, <logicalNotExpression>*.

String Comparison Operations compare or match the first given argument (left argument) with the second given argument (right argument). *$eq, $ne, $gt, $lt, $ge, $le* make an alphabetic string comparison. $**starts-with, $ends-with, $contains and $regex** check, if the first given argument is part of the second argument or if the first argument matches with the given REGEX.

Two operations additionally accept an uncast <ClaimPathAttribute>:

* In `<ClaimPathAttribute> $eq <ClaimPathStringOperand>` (or the reverse order), the selected claim value shall be a JSON string. `$eq` is true only when the complete selected string and the other string operand are equal. Equality is case-sensitive and performs no JSON serialization or type coercion. A selected value of another JSON type makes the operation indeterminate.
* In `$contains(<ClaimPathAttribute>, <ClaimPathStringOperand>)`, the selected claim value shall be an array containing only JSON strings. `$contains` is true only when one complete array element is equal to the other string operand. Array order and duplicate elements do not affect the result. An empty array produces false. A non-array value or an array containing a non-string element makes the operation indeterminate. This overload is exact array membership; it is not a substring search.

The existing string forms of `$eq` and `$contains` are unchanged. The ClaimPath-specific `$contains` form is directional: <ClaimPathAttribute> is the first operand. An uncast <ClaimPathAttribute> is not valid with `$ne`, ordered comparisons, `$starts-with`, `$ends-with`, or `$regex`.

<ClaimPathStringOperand> deliberately excludes an uncast <FieldIdentifier>. A field value shall establish its string type explicitly, for example `CLAIMPATH("/department/name") $eq str($sme#value)` or `$contains(CLAIMPATH("/realm_access/roles"), str($sme#requiredRole))`.

For a verified Claims Set containing `{"realm_access":{"roles":["reader","admin"]}}`, the following results apply:

[cols="2,1,3",options="header"]
|===
|Expression
|Result
|Reason

|`$contains(CLAIMPATH("/realm_access/roles"), "admin")`
|true
|One complete string-array element is equal.

|`$contains(CLAIMPATH("/realm_access/roles"), "min")`
|false
|Substrings within array elements do not match.

|`CLAIMPATH("/realm_access/roles/1") $eq "admin"`
|true
|The array index selects the scalar string `admin`.

|`CLAIMPATH("/realm_access/roles") $eq "admin"`
|indeterminate
|The selected value is an array, but this overload requires a string.

|`$contains(CLAIMPATH("/realm_access/missing"), "admin")`
|indeterminate
|The path does not resolve.
|===

Numerical Comparison Operations compare the first given argument (left argument) with the second given argument (right argument).
Since AAS also supports XS Datatypes Hex, Bool, DateTime and Time, related comparisons are available accordingly.

For specific comparisons datatypes can be casted to the other datatypes.
All explicit casts may take a <ClaimAttribute> or <ClaimPathAttribute> as input. For claim values, casts are strict type assertions followed, where applicable, by validation of the selected string's lexical representation. They do not coerce between JSON strings, numbers, and booleans. The following source types are accepted:

[cols="1,2,3",options="header"]
|===
|Cast
|Required selected JSON value
|Result

|`str(...)`
|string
|The unchanged string.

|`num(...)`
|number
|The JSON number, subject to the implementation's supported numeric range and precision.

|`bool(...)`
|boolean
|The unchanged Boolean value.

|`hex(...)`
|string conforming to <HexLiteral>
|The corresponding hex value.

|`dateTime(...)`
|string conforming to <DateTimeLiteral>
|The corresponding DateTime value.

|`time(...)`
|string conforming to <TimeLiteral>
|The corresponding Time value.
|===

A JSON array, object, or `null` cannot be cast. A string containing `"3"` is therefore not accepted by `num(...)`, and a string containing `"true"` is not accepted by `bool(...)`. Consequently, `str(CLAIMPATH("/name"))`, `num(CLAIMPATH("/assurance/level"))`, `hex(CLAIMPATH("/flags"))`, `bool(CLAIMPATH("/active"))`, `dateTime(CLAIMPATH("/validUntil"))`, and `time(CLAIMPATH("/accessTime"))` can be used wherever the corresponding typed operand is allowed. Casts do not implicitly select the first array element or serialize arrays or objects to text. A selected number whose value cannot be represented without violating the implementation's documented numeric limits shall produce an indeterminate result.
If a FieldIdentifier is used directly in a typed comparison, it is implicitly interpreted as the comparison type.
This implicit conversion is tried for all values addressed by the FieldIdentifier.
Values that cannot be converted are ignored for this FieldIdentifier evaluation.
If no addressed value can be converted, the comparison evaluates to FALSE.

Specific operations exist to extract parts from DateTime, i.e. $dayOfWeek, $dayOfMonth, $month, $year.
This enables access rules related to week days or specific times in the year.
EXAMPLE See xref:annex/text-access-rule-examples.adoc#example-time-based-submodel-id-pattern[weekday and time-based access].

An important special operation is $match, which can be used with any element containing a list of elements, e.g. semanticId[], specificAssetId[], SubmodelElementList or SubmodelElementCollection.
The list element is written with [] to express, that $match shall check if a certain expression is true for at least one element in the list.
FILTER defines one fragment restriction for a returned object, while FILTERLIST defines several fragment restrictions with independent conditions.

A formula can use all ABAC attributes defined in the ATTRIBUTES: section of the <<acl,ACL>>. A formula referring to an undefined attribute shall be indeterminate. Any type of error during the evaluation of an operation, including an unresolved <ClaimAttribute> or <ClaimPathAttribute>, a wrong selected JSON type, a non-string member of an array used by the ClaimPath-specific `$contains`, or an invalid cast, shall make that operation indeterminate.

Indeterminate is distinct from Boolean false and shall not be converted to false before evaluating an enclosing logical expression. In particular, `$not(indeterminate)` is indeterminate and cannot activate an ALLOW rule. Logical operators shall retain a result that has already been determined independently of an indeterminate operand:

[cols="2,1",options="header"]
|===
|Expression
|Result

|`$not(indeterminate)`
|indeterminate

|`$or(true, indeterminate)`
|true

|`$or(false, indeterminate)`
|indeterminate

|`$and(false, indeterminate)`
|false

|`$and(true, indeterminate)`
|indeterminate
|===

For logical operators with more than two operands, `$or` is true if any operand is true and is indeterminate if no operand is true and at least one operand is indeterminate. `$and` is false if any operand is false and is indeterminate if no operand is false and at least one operand is indeterminate. Formula evaluation is declarative. Implementations may short-circuit evaluation when the result has already been determined; an operand skipped by short-circuit evaluation is not considered to have produced an error.

The result of evaluating an ALLOW rule is Permit if its formula is true, NotApplicable if its formula is false, and Indeterminate if its formula is indeterminate. When multiple rules cover a request, the access rule model uses deny-unless-permit combination: access shall be granted if at least one applicable ALLOW rule evaluates to Permit; otherwise access shall be denied. An error in one rule therefore cannot by itself negate a separate rule that independently evaluates to Permit.

Implementations MAY impose limits on JSON Pointer length, nesting depth, or the number of array elements inspected to protect authorization evaluation from resource exhaustion. Such limits shall be documented. Exceeding a limit shall make the affected operation indeterminate; if no independently applicable rule evaluates to Permit, the final deny-unless-permit decision is Deny. Selected claim values SHOULD NOT be written to logs unless the deployment's data-protection policy explicitly permits it.

USEFORMULAS can be used to refer to a predefined formula (see <<reusable-definitions,Reusable Definitions>>).

.Railroad diagram for <UseFormula>
[[image-access-control-rules-formula-reference]]
image::access-control-rules-formula-reference.svg[width=642]

[[json-serialization]]
== JSON Serialization of Access Rule Model

The AAS Access Rule model can also be defined as a JSON schema.
Since the related JSON schema shall also allow automatic code generation, specific constraints must be fulfilled by such JSON schema.
The use of "oneof" is limited and type information for objects must be available.

It shall also be possible to check a JSON with the JSON schema.

Examples can be found in xref:annex/json-access-rule-examples.adoc[].
The JSON Schema artifacts and all JSON examples included in the specification are tested in the GitHub Actions CI/CD workflow "Validate spec artifacts".
This workflow runs `tools/validate_spec_artifacts.py` with the Python `jsonschema` package.
The script checks the JSON Schema files as JSON Schema Draft 7, resolves their `$ref` references, runs schema smoke tests for selected definitions, and validates every JSON example from the specification against the common access-rule JSON Schema and the access-rule-model JSON Schema.

The following schema meets such constraints:

[source,json,linenums]
----
include::partial$json/aas-queries-and-access-rules-schema.json[]
----

=== Explanation of the Access Rule Model JSON schema

==== General

The AAS Access Rule Model can be used to describe access rules.
Whether and how access rules are enforced is beyond the specification of the model for access control.
The parties involved are supposed to agree on governance and policies.

==== Access Rule Model

The Access Rules BNF grammar is expressed in JSON schema syntax.
Please refer to the detailed step by step explanation of the grammar.

[source,json,linenums]
----
include::partial$json/access-rule-model.json[]
----

==== Formulas and logical expressions

A detailed step by step explanation follows below the JSON schema code.

[source,json,linenums]
----
include::partial$json/formulas-and-logical-expressions.json[]
----

The provided JSON schema includes a _modelStringPattern_ starting with a $, so that the syntax of model elements can be checked by the schema, e.g. $sm.idShort.

String, number and boolean are supported by JSON itself.
Specific JSON Schema definitions are provided for datatypes Hex, DateTime and Time: _hexLiteralPattern_, _dateTimeLiteralPattern_ and _timeLiteralPattern_.
The DateTime and Time definitions use explicit regular expressions based on the AAS core meta verification functions `MatchesXsDateTime` and `MatchesXsTime`.
These verification functions correspond to the XSD-based DateTime and Time data types defined by the IDTA 01001 Part 1 Metamodel xref:bibliography.adoc#bib1[[1\]], especially https://industrialdigitaltwin.io/aas-specifications/IDTA-01001/v3.1/spec-metamodel/datatypes.html[Primitive and Simple Data Types].
For the generated AAS core meta verification definitions, see https://aas-core-works.github.io/aas-core-meta/v3/MatchesXsDateTime.html[MatchesXsDateTime] and https://aas-core-works.github.io/aas-core-meta/v3/MatchesXsTime.html[MatchesXsTime].
They are based on the XML Schema `xs:dateTime` and `xs:time` lexical representations defined in https://www.w3.org/TR/xmlschema-2/#dateTime[] and https://www.w3.org/TR/xmlschema-2/#time[], and the ISO 8601 formats referenced by XML Schema in https://www.w3.org/TR/xmlschema-2/#isoformats[].
Accordingly, DateTime and Time literals include seconds, may include fractional seconds, and may include a timezone (`Z` or an offset from `-14:00` to `+14:00`).
The end-of-day notation `24:00:00` is allowed, with only zero fractional seconds.
The day, month and year ranges in the BNF and JSON Schema are lexical constraints only.
Special calendar cases, such as February 29 in non-leap years or the 31st day of a month with only 30 days, shall still be rejected.

If an incoming value is provided in an incomplete ISO-like form, it shall be completed before it is serialized as a DateTime or Time literal.
If a Time value has no timezone information, it shall be interpreted as UTC and serialized with `Z`.
For example, the Time value `12:00:00` shall be interpreted and serialized as `12:00:00Z`.

_Value_ is used for comparisons and _StringValue_ is used for the specific string operations.
For type safety and automatic code generation, each possible type is available as an own object:

* String values can be given by _$field_, $__strVal__, a scalar $__attribute__ or $__strCast__.
* Numerical values can be given by $__numVal__ or $__numCast__.
* Hex values can be given by $__hexVal__ or $__hexCast__.
* Bool values can be given by _$boolean_ or $__boolCast__.
* DateTime values can be given by $__dateTimeVal__ or $__dateTimeCast__.
* Time values can be given by $__timeVal__ or $__timeCast__.

Casts convert values to the given type if possible.
DateTime casts use string operands; Time casts use string or DateTime operands.
The input of any cast may also be a $__attribute__ containing CLAIM or CLAIMPATH. Claim-value casts use the strict source-type rules defined in <<formulas>>; arrays, objects and `null` are invalid cast inputs.
Direct comparisons between two FieldIdentifier operands are not valid because the type of both fields would be implicit.
To compare two fields, at least one operand shall use an explicit cast, e.g. compare _$field_ to $__strCast__, $__numCast__, $__dateTimeCast__, or $__timeCast__.

Parts of DateTime values can be extracted as numbers:

* _$dayOfWeek_ extracts the day of week as number, starting with 0 for Sunday.
* _$dayOfMonth_, _$month_, _$year_ extract the related part as number.

Except for direct FieldIdentifier operands in typed comparisons, if a conversion or any other evaluated operation is invalid, that operation shall be indeterminate. An enclosing logical expression shall combine the result according to the three-valued logic defined in <<formulas>>.
Implementations SHOULD make a diagnostic available for an evaluated error without including selected claim values unless the deployment's data-protection policy permits their disclosure. An indeterminate final result shall not allow access and shall not expose filtered data.

To allow the use of different types in operations, arrays are used for parameters. _comparisonItems_ is used for comparisons and _stringItems_ is used for specific string operations.

_logicalExpressions_ and _match_ can be recursively nested.

For CLAIMPATH, _$eq_ additionally accepts a _claimPathValue_ paired with a _claimPathStringValue_. _$contains_ additionally accepts a _claimPathValue_ followed by a _claimPathStringValue_ and performs exact string-array membership. _claimPathStringValue_ excludes an uncast _$field_; a _$strCast_ is required for field values. Other direct typed operations exclude _claimPathValue_; an explicit cast shall be used instead.

== Exchange of Access Rules

Business Partners may be interested to exchange Access Rules.

As the AAS is a central point for data access, there is the need to support fine-grained access control that supports multiple roles as well as separate access control policies for individual elements or submodels in the AAS.
Access Control is based on Identity Management and can only be successfully implemented in a secure environment.
For this document, the focus lies on the supported access control model.

When AAS content is passed from one partner to another, this is typically related to a change in the access control domain of the partners involved (supplier, integrator, operator), i.e. the scope of the validity of access control policies.

In addition to the AAS content itself, also the defined access permissions have to be transferred between the partners due to the following two reasons:

[arabic]
. Access permissions to information elements of an AAS must be established in each access control domain.
. One partner must be able to pass a suggestion which access permissions should be established for the asset that is described in the AAS.

ABAC is a very flexible approach, that also encompasses role-based access as a role can be considered as one attribute in this context.
Other attributes might be the time-of-day, the location of the asset, the originating address and others.

As explained as an example above, a robot manufacturer suggests that for the robot the following roles shall be defined: machine setter, operator and a maintenance role.
Note that the roles have to be expressed by means of attributes of the AAS representing the robot.
He also suggests permissions for these roles, e.g. an installer (integrator) does have write-access to the program of the robot, but an operator does not.

Providing such suggested access rules, makes the integration of the operator much easier.
The operator can copy and paste the access rules into his AAS implementation and only needs to make adjustments.

The above example motivates that the access permission rules need to be passed from one access control domain to the other.

The enforcement of Access Rules is implementation specific.

This specification defines the text serialization of access rules and the JSON schema serialization of access rules.
The support of both is optional and not mandatory.

The JSON schema serialization is recommended.

Such serialization provides the possibility to exchange access rules.
An implementation may even store such serialized access rules in submodel elements BLOB or FILE, so that these can be accessed by the API and can be protected by access rules itself.

== API Queries and Access Rules

link:https://industrialdigitaltwin.io/aas-specifications/IDTA-01002/v3.1/query-language.html#query-language[Version 3.1 of the AAS API] defines queries and uses the same grammar and same JSON schema to define queries.
The JSON schema serialization is used in the related API operations.

In addition, using the same concepts will be needed for large amounts of AAS data.
Querying such large amounts of data and protecting such data with Access Rules requires optimized access of data.
Database queries may combine the filter expression provided by the client query with the FOMULAs of the Access Rules on the server.
