////
Copyright (c) 2025 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/).

SPDX-License-Identifier: CC-BY-4.0

Illustrations:
Plattform Industrie 4.0; Anna Salari, Publik. Agentur für Kommunikation GmbH, designed by Publik. Agentur für Kommunikation GmbH
////

= Part 4: Security (IDTA-01004)

====
This specification is part of the https://industrialdigitaltwin.org/en/content-hub/aasspecifications[Asset Administration Shell Specification series].
====

== Version

This is version 3.0.1 of the specification IDTA-01004.

Previous version: 3.0.

[#metamodel-versions]
== Metamodel Versions

This document uses the following parts and versions of the “Specification of the Asset Administration Shell” series:

* IDTA-01001 Part 1: Metamodel in version 3.2 xref:bibliography.adoc#bib1[[1\]]
* IDTA-01002 Part 2: Application Programming Interfaces in version 3.2 xref:bibliography.adoc#bib2[[2\]]
* IDTA-01003-a Part 3a: Data Specification – IEC 61360 in version 3.1 xref:bibliography.adoc#bib3[[3\]]

If there are bugfixes of the parts, these shall be used.

[#cross-spec-alignment]
=== Alignment with other AAS Specifications

This version of IDTA-01004 (v3.1) is designed to be used together with the following companion specifications:

[cols="2,2,3",options="header"]
|===
| Specification | Aligned Version | Notes

| IDTA-01001 Part 1: Metamodel
| v3.2
| Defines the classes referenced by FieldIdentifier prefixes (`$aas`, `$sm`, `$sme`, `$cd`, `$aasdesc`, `$smdesc`).

| IDTA-01002 Part 2: Application Programming Interfaces
| v3.2
| HTTP/REST API and AAS Query Language. IDTA-01002 and IDTA-01004 share the same BNF grammar and JSON Schema for formula expressions; the Query Language chapter in IDTA-01002 is normative for formula semantics.
|===

Bugfix (patch) releases of aligned specifications MAY be substituted. Implementations conforming to this version of IDTA-01004 SHOULD declare which versions of IDTA-01001 and IDTA-01002 they implement.

== Notice

Copyright: Industrial Digital Twin Association e.V. (IDTA)

DOI: https://doi.org/10.62628/IDTA.01004-3-0-1

IDTA Number: IDTA-01004

Version: 3.0.1

This work is licensed under a
https://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 International License].

SPDX-License-Identifier: CC-BY-4.0

July 2025

== How to Get in Contact

Contact: https://industrialdigitaltwin.org/en/contact[IDTA]

Sources: https://github.com/admin-shell-io/aas-specs-security[GitHub]

Feedback:

* https://github.com/admin-shell-io/aas-specs-security/issues/new/choose[new issues, bugs]

* https://github.com/admin-shell-io/questions-and-answers[Questions and Answers]


[[editorial-notes]]
== Editorial Notes

=== History

This document (release candidate for review) was produced from May 2023 to January 2025 by the Task Force “Security” of the working group "Open Technology" in the Industrial Digital Twin Association (IDTA).

Earlier content of this document was developed in the Plattform Industrie 4.0 working group “Reference Architectures, Standards and Norms“, especially Clause 7 “Security” of the Part 1 specification Version 3.0RC02 and the discussion paper “Secure Download Service” xref:bibliography.adoc#bib6[[6\]].

include::./shared/versioning.adoc[]

include::./shared/conformance.adoc[]
