////
Copyright (c) 2025 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/).

SPDX-License-Identifier: CC-BY-4.0

Illustrations:
Plattform Industrie 4.0; Anna Salari, Publik. Agentur für Kommunikation GmbH, designed by Publik. Agentur für Kommunikation GmbH
////

= Examples of Access Rules in JSON serialization

For an explanation of the examples, see xref:annex/text-access-rule-examples.adoc[Examples in text BNF].

== EXAMPLE 1: Allow READ access for Anonymous 

[source,json,linenums]
----
include::partial$examples/allow-read-complete-api.json[]
----

== EXAMPLE 2: Allow READ access for Anonymous to list of semanticIDs for submodels

[source,json,linenums]
----
include::partial$examples/allow-read-list-semanticids.json[]
----

== EXAMPLE 3: Allow EXECUTE of API operations only if machine not-running

[source,json,linenums]
----
include::partial$examples/allow-read-list-semanticids-machinestate.json[]
----

== EXAMPLE 4: Allow READ and UPDATE for specific authenticated users

[source,json,linenums]
----
include::partial$examples/allow-read-update-users.json[]
----

== EXAMPLE 5: Allow READ and UPDATE for specific Submodel "submodel1"

[source,json,linenums]
----
include::partial$examples/allow-read-update-submodel.json[]
----

== EXAMPLE 6: Reuse of ACL, OBJECT and FORMULA

[source,json,linenums]
----
include::partial$examples/reuse-acl-object-formula.json[]
----

== EXAMPLE 7:Example for authenticated users with a specific BusinessPartnerNumber

[source,json,linenums]
----
include::partial$examples/bpn.json[]
----

== EXAMPLE 8: Example for authenticated users of a company 

[source,json,linenums]
----
include::partial$examples/allow-read-all-users-of-company-for-submodel.json[]
----

== EXAMPLE 9: Example with access constraints 

[source,json,linenums]
----
include::partial$examples/allow-read-submodels-id-pattern.json[]
----

== EXAMPLE 10: Example with allowing creation within Submodel

[source,json,linenums]
----
include::partial$examples/allow-create-only-specific.json[]
----

== EXAMPLE 11: Example with FILTER statement

[source,json,linenums]
----
include::partial$examples/filter.json[]
----

== EXAMPLE 12: Example with Reference Attribute and state-dependent filtering

[source,json,linenums]
----
include::partial$examples/reference-machine-state-filter.json[]
----

== EXAMPLE 13: Nested and multi-valued access-token claims

[source,json,linenums]
----
include::partial$examples/nested-claim-path.json[]
----
