////
Copyright (c) 2025 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/).

SPDX-License-Identifier: CC-BY-4.0

Illustrations:
Plattform Industrie 4.0; Anna Salari, Publik. Agentur für Kommunikation GmbH, designed by Publik. Agentur für Kommunikation GmbH
////

= Examples of Access Rules in text serialization

[[example-anonymous-complete-api]]
== Allow READ access for Anonymous to complete API

[source,bnf,linenums]
----
include::partial$examples/allow-read-complete-api.bnf[]
----

[[example-anonymous-semanticids]]
== Allow READ access for Anonymous to list of semanticIDs for submodels

[source,bnf,linenums]
----
include::partial$examples/allow-read-list-semanticids.bnf[]
----

== Allow EXECUTE of API operations only if machine not-running

[source,bnf,linenums]
----
include::partial$examples/allow-read-list-semanticids-machinestate.bnf[]
----

[[example-authenticated-users]]
== Allow READ and UPDATE for specific authenticated users

[source,bnf,linenums]
----
include::partial$examples/allow-read-update-users.bnf[]
----

== Allow READ and UPDATE for specific submodel "submodel1"

[source,bnf,linenums]
----
include::partial$examples/allow-read-update-submodel.bnf[]
----

[[example-reuse-acl-object-formula]]
== Reuse of ACL, OBJECT and FORMULA

[source,bnf,linenums]
----
include::partial$examples/reuse-acl-object-formula.bnf[]
----

[[example-business-partner-number]]
== Example with BusinessPartnerNumber

[source,bnf,linenums]
----
include::partial$examples/bpn.bnf[]
----

== Allow READ for all authenticated users of a company for submodels Nameplate and TechnicalData

[source,bnf,linenums]
----
include::partial$examples/allow-read-all-users-of-company-for-submodel.bnf[]
----

[[allow-read-submodels-id-pattern]]
[[example-time-based-submodel-id-pattern]]
== Allow READ to all Submodels with ID pattern for all authenticated users of a company for submodels with Nameplate and TechnicalData on weekdays from 09:00:00Z-17:00:00Z

[source,bnf,linenums]
----
include::partial$examples/allow-read-submodels-id-pattern.bnf[]
----

== Allow only to add elements to the CertificateSet in any Submodel

[source,bnf,linenums]
----
include::partial$examples/allow-create-only-specific.bnf[]
----

[[example-filter-statement]]
== Example with FILTER statement

[source,bnf,linenums]
----
include::partial$examples/filter.bnf[]
----

[[example-reference-machine-state-filter]]
== Example with Reference Attribute and state-dependent filtering

[source,bnf,linenums]
----
include::partial$examples/reference-machine-state-filter.bnf[]
----
