<AllAccessPermissionRules> ::=
    <AllAccessPermissionDefs>
    ( <AccessPermissionRule> <Ws> )*

<AllAccessPermissionDefs> ::=
    <AllAccessDefAttributes>
    <AllAccessDefAcls>
    <AllAccessDefObjects>
    <AllAccessDefFormulas>

<AllAccessDefAttributes> ::=
    ( "DEFATTRIBUTES" <Ws> <StringLiteral> <Ws> <AttributeGroup> <Ws> )*

<AllAccessDefAcls> ::=
    ( "DEFACLS" <Ws> <StringLiteral> <Ws> <ACL> <Ws> )*

<AllAccessDefObjects> ::=
    ( "DEFOBJECTS" <Ws> <StringLiteral> <Ws> <ObjectGroup> <Ws> )*

<AllAccessDefFormulas> ::=
    ( "DEFFORMULAS" <Ws> <StringLiteral> <Ws> <LogicalExpression> <Ws> )*

<AccessPermissionRule> ::=
    <AccessAccessRule>
    <AccessObjects>
    <AccessFormula>
    <Filter>

<AccessAccessRule> ::=
    "ACCESSRULE:" <Ws> ( <ACL> | <UseACL> ) <Ws>

<AccessObjects> ::=
    "OBJECTS:" <Ws>
    ( <SingleObject> <Ws> )*
    ( <UseObjectGroup> <Ws> )*

<AccessFormula> ::=
    ( "FORMULA:" <Ws> <LogicalExpression> <Ws> ) |
    ( <UseFormula> <Ws> )

<Filter> ::=
    ( "FILTERLIST:" <Ws> ( <SecurityQueryFilter> <Ws> )+ )?
