<AllAccessPermissionRules> ::=
    <AllAccessPermissionDefs>
    ( <AccessPermissionRule> <Ws> )*

<AllAccessPermissionDefs> ::=
    <AllAccessDefAttributes>
    <AllAccessDefAcls>
    <AllAccessDefObjects>
    <AllAccessDefFormulas>

<AllAccessDefAttributes> ::=
    ( "DEFATTRIBUTES" <Ws> <StringLiteral> <Ws> <AttributeGroup> <Ws> )*

<AllAccessDefAcls> ::=
    ( "DEFACLS" <Ws> <StringLiteral> <Ws> <ACL> <Ws> )*

<AllAccessDefObjects> ::=
    ( "DEFOBJECTS" <Ws> <StringLiteral> <Ws> <ObjectGroup> <Ws> )*

<AllAccessDefFormulas> ::=
    ( "DEFFORMULAS" <Ws> <StringLiteral> <Ws> <LogicalExpression> <Ws> )*

<AccessPermissionRule> ::=
    <AccessAccessRule>
    <AccessObjects>
    <AccessFormula>
    <Filter>

<AccessAccessRule> ::=
    "ACCESSRULE:" <Ws> ( <ACL> | <UseACL> ) <Ws>

<AccessObjects> ::=
    "OBJECTS:" <Ws>
    ( <SingleObject> <Ws> )*
    ( <UseObjectGroup> <Ws> )*

<AccessFormula> ::=
    ( "FORMULA:" <Ws> <LogicalExpression> <Ws> ) |
    ( <UseFormula> <Ws> )

<Filter> ::=
    (
        ( "FILTER:" <Ws> <SecurityQueryFilter> <Ws> )? |
        ( "FILTERLIST:" <Ws> ( <SecurityQueryFilter> <Ws> )* )?
    )

<SecurityQueryFilter> ::=
    ( "FRAGMENT:" <Ws> <FieldIdentifierFragment> <Ws> )
    (
        ( "CONDITION:" <Ws> <LogicalExpression> <Ws> ) |
        ( <UseFormula> <Ws> )
    )

<ACL> ::=
    <AclAttributes>
    "RIGHTS:" <Ws> <Right> <Ws> ( <Right> <Ws> )*
    "ACCESS:" <Ws> <Access> <Ws>

<AclAttributes> ::=
    "ATTRIBUTES:" <Ws>
    ( <SingleAttribute> <Ws> )*
    ( <UseAttributeGroup> <Ws> )*

<UseACL> ::= "USEACL" <Ws> <StringLiteral> <Ws>

<Right> ::= "CREATE" | "READ" | "UPDATE" | "DELETE" | "EXECUTE" | "VIEW" | "ALL"

<Access> ::= "ALLOW" | "DISABLED"

<SingleAttribute> ::= <ClaimAttribute> | <GlobalAttribute> | <ReferenceAttribute>

<ClaimAttribute> ::= "CLAIM" <Ws> "(" <Ws> <ClaimLiteral> <Ws> ")"

<GlobalAttribute> ::=
    "GLOBAL" <Ws> "(" <Ws>
    ( "LOCALNOW" | "UTCNOW" | "CLIENTNOW" | "ANONYMOUS" )
    <Ws> ")"

<DateTimeGlobalAttribute> ::=
    "GLOBAL" <Ws> "(" <Ws>
    ( "LOCALNOW" | "UTCNOW" | "CLIENTNOW" )
    <Ws> ")"

<ReferenceAttribute> ::=
    "REFERENCE("
        "$aas" <IdentifierInstance> "#" <FieldsAAS> |
        "$sm" <IdentifierInstance> "#" <FieldsSM> |
        "$cd" <IdentifierInstance> "#" <FieldsCD> |
        "$sme" <IdentifierInstance> "." <IdShortPath> "#" <FieldsSME>
    ")"

<AttributeGroup> ::=
    ( <SingleAttribute> <Ws> )*
    ( <UseAttributeGroup> <Ws> )*

<UseAttributeGroup> ::= "USEATTRIBUTES" <Ws> <StringLiteral> <Ws>

<SingleObject> ::=
    <RouteObject> |
    <IdentifiableObject> |
    <ReferableObject> |
    <FragmentObject> |
    <DescriptorObject>

<RouteObject> ::= "ROUTE" <Ws> <RouteLiteral> <Ws>

<IdentifierInstance> ::= "(" <StringLiteral> ")"
<IdentifierInstanceOrAll> ::= <IdentifierInstance> | "(\"*\")"

<IdentifiableObject> ::=
    "IDENTIFIABLE" <Ws> ( "$aas" | "$sm" | "$cd" ) <IdentifierInstanceOrAll>

<ReferableObject> ::= "REFERABLE" <Ws> "$sme" <IdentifierInstanceOrAll> "." <IdShortPath>

<FragmentObject> ::= "FRAGMENT" <Ws> <FragmentLiteral> <Ws>

<DescriptorObject> ::= "DESCRIPTOR" <Ws> ( "$aasdesc" | "$smdesc" ) <IdentifierInstanceOrAll>

<ObjectGroup> ::=
    ( <SingleObject> <Ws> )* |
    ( <UseObjectGroup> <Ws> )*

<UseObjectGroup> ::= "USEOBJECTS" <Ws> <StringLiteral> <Ws>

<UseFormula> ::= "USEFORMULA" <Ws> <StringLiteral> <Ws>

<LogicalExpression> ::=
    <LogicalNestedExpression> |
    <LogicalOrExpression> |
    <LogicalAndExpression> |
    <LogicalNotExpression> |
    <MatchExpression> |
    <BoolLiteral> |
    <CastToBool> |
    <SingleComparison>

<LogicalNestedExpression> ::= "(" <Ws> <LogicalExpression> ")" <Ws>

<LogicalOrExpression> ::=
    "$or" <Ws> "(" <Ws> <LogicalExpression>
    ( "," <Ws> <LogicalExpression> )+ ")" <Ws>

<LogicalAndExpression> ::=
    "$and" <Ws> "(" <Ws> <LogicalExpression>
    ( "," <Ws> <LogicalExpression> )+ ")" <Ws>

<LogicalNotExpression> ::= "$not" <Ws> "(" <Ws> <LogicalExpression> ")" <Ws>

<MatchExpression> ::=
    "$match" <Ws> "(" <Ws>
    ( <SingleComparison> | <MatchExpression> )
    ( "," <Ws> ( <SingleComparison> | <MatchExpression> ) )*
    ")" <Ws>

<SingleComparison> ::=
    <StringComparison> |
    <NumericalComparison> |
    <HexComparison> |
    <BoolComparison> |
    <DateTimeComparison> |
    <TimeComparison>

<AllComparisons> ::= "$eq" | "$ne" | "$gt" | "$lt" | "$ge" | "$le"

<StringComparison> ::=
    (
        ( "$starts-with" | "$ends-with" | "$contains" | "$regex" )
        <Ws> "(" <Ws> <StringOperand> <Ws> "," <Ws> <StringOperand> <Ws> ")" <Ws>
    ) |
    ( <StringOperand> <Ws> <AllComparisons> <Ws> <StringNonFieldOperand> <Ws> ) |
    ( <StringNonFieldOperand> <Ws> <AllComparisons> <Ws> <StringOperand> <Ws> )

<NumericalComparison> ::=
    ( <NumericalOperand> <Ws> <AllComparisons> <Ws> <NumericalOperand> <Ws> ) |
    ( <NumericalOperand> <Ws> <AllComparisons> <Ws> <FieldIdentifier> <Ws> ) |
    ( <FieldIdentifier> <Ws> <AllComparisons> <Ws> <NumericalOperand> <Ws> )

<HexComparison> ::=
    ( <HexOperand> <Ws> <AllComparisons> <Ws> <HexOperand> <Ws> ) |
    ( <HexOperand> <Ws> <AllComparisons> <Ws> <FieldIdentifier> <Ws> ) |
    ( <FieldIdentifier> <Ws> <AllComparisons> <Ws> <HexOperand> <Ws> )

<BoolComparison> ::=
    ( <BoolOperand> <Ws> ( "$eq" | "$ne" ) <Ws> <BoolOperand> <Ws> ) |
    ( <BoolOperand> <Ws> ( "$eq" | "$ne" ) <Ws> <FieldIdentifier> <Ws> ) |
    ( <FieldIdentifier> <Ws> ( "$eq" | "$ne" ) <Ws> <BoolOperand> <Ws> )

<DateTimeComparison> ::=
    ( <DateTimeOperand> <Ws> <AllComparisons> <Ws> <DateTimeOperand> <Ws> ) |
    ( <DateTimeOperand> <Ws> <AllComparisons> <Ws> <FieldIdentifier> <Ws> ) |
    ( <FieldIdentifier> <Ws> <AllComparisons> <Ws> <DateTimeOperand> <Ws> )

<DateTimeToNum> ::=
    ( "$dayOfWeek" | "$dayOfMonth" | "$month" | "$year" )
    <Ws> "(" <Ws> <DateTimeOperand> <Ws> ")" <Ws>

<TimeComparison> ::=
    ( <TimeOperand> <Ws> <AllComparisons> <Ws> <TimeOperand> <Ws> ) |
    ( <TimeOperand> <Ws> <AllComparisons> <Ws> <FieldIdentifier> <Ws> ) |
    ( <FieldIdentifier> <Ws> <AllComparisons> <Ws> <TimeOperand> <Ws> )

<Operand> ::=
    <StringOperand> |
    <NumericalOperand> |
    <HexOperand> |
    <BoolOperand> |
    <DateTimeOperand> |
    <TimeOperand>

<StringOperand> ::= <FieldIdentifier> | <StringLiteral> | <CastToString> | <SingleAttribute>

<StringNonFieldOperand> ::= <StringLiteral> | <CastToString> | <SingleAttribute>

<NumericalOperand> ::= <NumericalLiteral> | <CastToNumerical> | <DateTimeToNum>

<HexOperand> ::= <HexLiteral> | <CastToHex>

<BoolOperand> ::= <BoolLiteral> | <CastToBool>

<DateTimeOperand> ::= <DateTimeLiteral> | <CastToDateTime> | <DateTimeGlobalAttribute>

<TimeOperand> ::= <TimeLiteral> | <CastToTime>

<CastToString> ::= "str" <Ws> "(" <Ws> <Operand> <Ws> ")" <Ws>

<CastToNumerical> ::= "num" <Ws> "(" <Ws> <Operand> <Ws> ")" <Ws>

<CastToHex> ::= "hex" <Ws> "(" <Ws> <Operand> <Ws> ")" <Ws>

<CastToBool> ::= "bool" <Ws> "(" <Ws> <Operand> <Ws> ")" <Ws>

<CastToDateTime> ::= "dateTime" <Ws> "(" <Ws> <StringOperand> <Ws> ")" <Ws>

<CastToTime> ::= "time" <Ws> "(" <Ws> ( <StringOperand> | <DateTimeOperand> ) <Ws> ")" <Ws>

<DateTimeLiteral> ::= <Datetime> <Ws>
<TimeLiteral> ::= <Time> ( <Timezone> )? <Ws>
<Datetime> ::= <Date> "T" <Time> ( <Timezone> )?
<Date> ::= <Year> "-" <Month> "-" <Day>
<Year> ::=
    ( "-" )?
    ( ( [1-9] <Digit> <Digit> <Digit> <Digit>* ) | ( "0" <Digit> <Digit> <Digit> ) )
<Month> ::= ( "0" [1-9] ) | ( "1" [0-2] )
<Day> ::= ( "0" [1-9] ) | ( ( "1" | "2" ) <Digit> ) | ( "3" ( "0" | "1" ) )
<Time> ::= <NormalTime> | <EndOfDayTime>
<NormalTime> ::= <Hour> ":" <Minute> ":" <Second> ( "." <Fraction> )?
<EndOfDayTime> ::= "24:00:00" ( "." "0"+ )?
<Timezone> ::=
    (
        "Z" |
        ( "+" | "-" ) ( ( ( "0" <Digit> | "1" [0-3] ) ":" <Minute> ) | "14:00" )
    )
<Hour> ::= ( "0" | "1" ) <Digit> | "2" [0-3]
<Minute> ::= [0-5] <Digit>
<Second> ::= [0-5] <Digit>
<Fraction> ::= <Digit>+

<Digit> ::= [0-9]
<StringLiteral> ::=
    "\""
    (
        [A-Z] | [a-z] | [0-9] | "/" | "*" | "[" | "]" | "(" | ")" |
        " " | "_" | "@" | "#" | "\\" | "+" | "-" | "." | "," | ":" | "$" | "^"
    )+
    "\""
<ClaimLiteral> ::= <StringLiteral>
<RouteLiteral> ::= <StringLiteral>
<IdentifiableLiteral> ::= <StringLiteral>
<ReferableLiteral> ::= <StringLiteral>
<FragmentLiteral> ::= <StringLiteral>
<DescriptorLiteral> ::= <StringLiteral>
<NumericalLiteral> ::=
    ( "+" | "-" )?
    ( [0-9]+ ( "." [0-9]* )? | "." [0-9]+ )
    ( ( "e" | "E" ) ( "+" | "-" )? [0-9]+ )?
<HexLiteral> ::= "16#" ( [0-9] | [A-F] )+
<BoolLiteral> ::= "true" | "false"

<FieldIdentifier> ::=
    <FieldIdentifierAAS> |
    <FieldIdentifierSM> |
    <FieldIdentifierSME> |
    <FieldIdentifierCD> |
    <FieldIdentifierAasDescriptor> |
    <FieldIdentifierSmDescriptor>

<FieldIdentifierAAS> ::= "$aas#" <FieldsAAS>
<FieldIdentifierSM> ::= "$sm#" <FieldsSM>
<FieldIdentifierSME> ::= "$sme" ( "." <IdShortPath> )? "#" <FieldsSME>
<FieldIdentifierCD> ::= "$cd#" <FieldsCD>
<FieldIdentifierAasDescriptor> ::= "$aasdesc#" <FieldsAasDescriptor>
<FieldIdentifierSmDescriptor> ::= "$smdesc#" <SmDescriptorClause>

<FieldsAAS> ::=
    "idShort" |
    "id" |
    "assetInformation.assetKind" |
    "assetInformation.assetType" |
    "assetInformation.globalAssetId" |
    "assetInformation." <SpecificAssetIdsClause> |
    "submodels" ( "[" <ArrayIndex>? "]" ) ( "." <ReferenceClause> )?

<FieldsSM> ::= <SemanticIdClause> | <SupplementalSemanticIdClause> | "idShort" | "id"

<FieldsSME> ::=
    <SemanticIdClause> |
    <SupplementalSemanticIdClause> |
    "idShort" |
    "value" |
    "valueType" |
    "language"

<FieldsCD> ::= "idShort" | "id"

<FieldsAasDescriptor> ::=
    "idShort" |
    "id" |
    "assetKind" |
    "assetType" |
    "globalAssetId" |
    <SpecificAssetIdsClause> |
    "endpoints" ( "[" <ArrayIndex>? "]" ) "." <EndpointClause> |
    "submodelDescriptors" ( "[" <ArrayIndex>? "]" ) "." <SmDescriptorClause>

<SmDescriptorClause> ::=
    <SemanticIdClause> |
    <SupplementalSemanticIdClause> |
    "idShort" |
    "id" |
    "endpoints" ( "[" <ArrayIndex>? "]" ) "." <EndpointClause>

<EndpointClause> ::= "interface" | "protocolinformation.href"

<ReferenceClause> ::= "type" | "keys" ( "[" <ArrayIndex>? "]" ) ( ".type" | ".value" )
<SemanticIdClause> ::= "semanticId" | "semanticId." <ReferenceClause>
<SupplementalSemanticIdClause> ::= "supplementalSemanticIds" ( "[" <ArrayIndex>? "]" )? ( "." <ReferenceClause> )?
<SpecificAssetIdsClause> ::=
    "specificAssetIds" ( "[" <ArrayIndex>? "]" )
    (
        ".name" |
        ".value" |
        ".externalSubjectId" |
        ".externalSubjectId." <ReferenceClause>
    )

<FieldIdentifierFragment> ::=
    <FieldIdentifierAASFragment> |
    <FieldIdentifierSMFragment> |
    <FieldIdentifierSMEFragment> |
    <FieldIdentifierCDFragment> |
    <FieldIdentifierAasDescriptorFragment> |
    <FieldIdentifierSmDescriptorFragment>

<FieldIdentifierAASFragment> ::=
    "$aas#"
    (
        "idShort" |
        "assetInformation.assetType" |
        "assetInformation.globalAssetId" |
        "assetInformation." <SpecificAssetIdsClauseFragment> |
        <SubmodelsClauseFragment>
    )

<FieldIdentifierSMFragment> ::=
    "$sm#" ( <SemanticIdClauseFragment> | <SupplementalSemanticIdClauseFragment> | "idShort" )

<FieldIdentifierSMEFragment> ::=
    "$sme" ( "." <IdShortPath> )?
    (
        "#"
        (
            <SemanticIdClauseFragment> |
            <SupplementalSemanticIdClauseFragment> |
            "idShort" |
            "value" |
            "valueType" |
            "language"
        )
    )?

<FieldIdentifierCDFragment> ::= "$cd#" "idShort"

<FieldIdentifierAasDescriptorFragment> ::=
    "$aasdesc#"
    (
        "idShort" |
        "description" |
        "displayName" |
        "extension" |
        "administration" |
        "assetKind" |
        "assetType" |
        "globalAssetId" |
        <SpecificAssetIdsClauseFragment> |
        <EndpointClauseFragment> |
        <SubmodelDescriptorsClauseFragment>
    )

<FieldIdentifierSmDescriptorFragment> ::= "$smdesc#" <SmDescriptorClauseFragment>

<SpecificAssetIdsClauseFragment> ::=
    "specificAssetIds" |
    "specificAssetIds" ( "[" <ArrayIndex>? "]" )
    ( ".externalSubjectId" ( "." <ReferenceClauseFragment> )? )?

<SubmodelsClauseFragment> ::=
    "submodels" |
    "submodels" ( "[" <ArrayIndex>? "]" ) ( "." <ReferenceClauseFragment> )?

<SubmodelDescriptorsClauseFragment> ::=
    "submodelDescriptors" |
    "submodelDescriptors" ( "[" <ArrayIndex>? "]" ) ( "." <SmDescriptorClauseFragment> )?

<SmDescriptorClauseFragment> ::=
    <SemanticIdClauseFragment> |
    <SupplementalSemanticIdClauseFragment> |
    "idShort" |
    <EndpointClauseFragment>

<EndpointClauseFragment> ::= "endpoints" ( "[" <ArrayIndex>? "]" )?

<SemanticIdClauseFragment> ::= "semanticId" | "semanticId." <ReferenceClauseFragment>

<SupplementalSemanticIdClauseFragment> ::=
    "supplementalSemanticIds" ( "[" <ArrayIndex>? "]" ( "." <ReferenceClauseFragment> )? )?

<ReferenceClauseFragment> ::= "keys" ( "[" <ArrayIndex>? "]" )?

<IdShortPath> ::= ( <IdShort> ( "[" <ArrayIndex>? "]" )* ( "." <IdShortPath> )* )
<IdShort> ::=
    (
        ( [a-z] | [A-Z] )
        ( [a-z] | [A-Z] | [0-9] | "_" | "-" )*
        ( [a-z] | [A-Z] | [0-9] | "_" )
    )
<ArrayIndex> ::= "0" | ( [1-9] [0-9]* )

<Ws> ::= ( " " | "\t" | "\r" | "\n" )*
