<ACL> ::=
    "ATTRIBUTES:" <Ws>
    ( <SingleAttribute> <Ws> )*
    ( <UseAttributeGroup> <Ws> )*
    "RIGHTS:" <Ws> <Right> <Ws> ( <Right> <Ws> )*
    "ACCESS:" <Ws> <Access> <Ws>

<UseACL> ::=
    "USEACL" <Ws> <StringLiteral> <Ws>

<Right> ::=
    "CREATE" | "READ" | "UPDATE" | "DELETE" | "EXECUTE" | "VIEW" | "ALL"

<Access> ::=
    "ALLOW" | "DISABLED"
