<SingleAttribute> ::=
    <ClaimAttribute> | <GlobalAttribute> | <ReferenceAttribute>

<ClaimAttribute> ::=
    "CLAIM" <Ws> "(" <Ws> <ClaimLiteral> <Ws> ")"

<GlobalAttribute> ::=
    "GLOBAL" <Ws> "(" <Ws> ( "LOCALNOW" | "UTCNOW" | "CLIENTNOW" | "ANONYMOUS" ) <Ws> ")"

<ReferenceAttribute> ::=
    "REFERENCE(" (
    ("$aas" <IdentifierInstance> "#" <FieldsAAS> ) |
    ("$sm" <IdentifierInstance> "#" <FieldsSM> ) |
    ("$cd" <IdentifierInstance> "#" <FieldsCD> ) |
    ("$sme" <IdentifierInstance> "." <IdShortPath> "#" <FieldsSME> )
    ) ")"

<AttributeGroup> ::=
    ( <SingleAttribute> <Ws> )*
    ( <UseAttributeGroup> <Ws> )*

<UseAttributeGroup> ::=
    "USEATTRIBUTES" <Ws> <StringLiteral> <Ws>
