<UseFormula> ::=
    "USEFORMULA" <Ws> <StringLiteral> <Ws>

<LogicalExpression> ::= <LogicalNestedExpression> | <LogicalOrExpression> | <LogicalAndExpression> |
<LogicalNotExpression> | <MatchExpression> | <BoolLiteral> | <CastToBool> | <SingleComparison>
<LogicalNestedExpression> ::= "(" <Ws> <LogicalExpression> ")" <Ws>
<LogicalOrExpression> ::= "$or" <Ws> "(" <Ws> <LogicalExpression> ( "," <Ws> <LogicalExpression> )+ ")" <Ws>
<LogicalAndExpression> ::= "$and" <Ws> "(" <Ws> <LogicalExpression> ( "," <Ws> <LogicalExpression> )+ ")" <Ws>
<LogicalNotExpression> ::= "$not" <Ws> "(" <Ws> <LogicalExpression> ")" <Ws>

<MatchExpression> ::= ( "$match" <Ws> "(" <Ws> ( <SingleComparison> | <MatchExpression> ) ( "," <Ws> ( <SingleComparison> | <MatchExpression> ) )* ")" <Ws> )

<SingleComparison> ::=
    <ClaimPathEqualityComparison> |
    <StringComparison> |
    <NumericalComparison> |
    <HexComparison> |
    <BoolComparison> |
    <DateTimeComparison> |
    <TimeComparison>

<AllComparisons> ::= ( "$eq" | "$ne" | "$gt" | "$lt" | "$ge" | "$le" )

<ClaimPathEqualityComparison> ::=
    ( <ClaimPathAttribute> <Ws> "$eq" <Ws> <ClaimPathStringOperand> <Ws> ) |
    ( <ClaimPathStringOperand> <Ws> "$eq" <Ws> <ClaimPathAttribute> <Ws> )

<StringComparison> ::=
    <ContainsComparison> |
    ( ( "$starts-with" | "$ends-with" | "$regex") <Ws> "(" <Ws> <StringOperand> <Ws> "," <Ws> <StringOperand> <Ws> ")" <Ws> ) |
    ( <StringOperand> <Ws> <AllComparisons> <Ws> <StringNonFieldOperand> <Ws> ) |
    ( <StringNonFieldOperand> <Ws> <AllComparisons> <Ws> <StringOperand> <Ws> )

<ContainsComparison> ::=
    ( "$contains" <Ws> "(" <Ws> <StringOperand> <Ws> "," <Ws> <StringOperand> <Ws> ")" <Ws> ) |
    ( "$contains" <Ws> "(" <Ws> <ClaimPathAttribute> <Ws> "," <Ws> <ClaimPathStringOperand> <Ws> ")" <Ws> )

<NumericalComparison> ::=
    ( <NumericalOperand> <Ws> <AllComparisons> <Ws> <NumericalOperand> <Ws> ) |
    ( <NumericalOperand> <Ws> <AllComparisons> <Ws> <FieldIdentifier> <Ws> ) |
    ( <FieldIdentifier> <Ws> <AllComparisons> <Ws> <NumericalOperand> <Ws> )

<HexComparison> ::=
    ( <HexOperand> <Ws> <AllComparisons> <Ws> <HexOperand> <Ws> ) |
    ( <HexOperand> <Ws> <AllComparisons> <Ws> <FieldIdentifier> <Ws> ) |
    ( <FieldIdentifier> <Ws> <AllComparisons> <Ws> <HexOperand> <Ws> )

<BoolComparison> ::=
    ( <BoolOperand> <Ws> ( "$eq" | "$ne" ) <Ws> <BoolOperand> <Ws> ) |
    ( <BoolOperand> <Ws> ( "$eq" | "$ne" ) <Ws> <FieldIdentifier> <Ws> ) |
    ( <FieldIdentifier> <Ws> ( "$eq" | "$ne" ) <Ws> <BoolOperand> <Ws> )

<DateTimeComparison> ::=
    ( <DateTimeOperand> <Ws> <AllComparisons> <Ws> <DateTimeOperand> <Ws> ) |
    ( <DateTimeOperand> <Ws> <AllComparisons> <Ws> <FieldIdentifier> <Ws> ) |
    ( <FieldIdentifier> <Ws> <AllComparisons> <Ws> <DateTimeOperand> <Ws> )

<DateTimeToNum> ::=
    ( "$dayOfWeek" | "$dayOfMonth" | "$month" | "$year" ) <Ws> "(" <Ws> <DateTimeOperand> <Ws> ")" <Ws>

<TimeComparison> ::=
    ( <TimeOperand> <Ws> <AllComparisons> <Ws> <TimeOperand> <Ws> ) |
    ( <TimeOperand> <Ws> <AllComparisons> <Ws> <FieldIdentifier> <Ws> ) |
    ( <FieldIdentifier> <Ws> <AllComparisons> <Ws> <TimeOperand> <Ws> )

<Operand> ::= <StringOperand> | <NumericalOperand> | <HexOperand> | <BoolOperand> | <DateTimeOperand> | <TimeOperand>

<StringOperand> ::=
    <FieldIdentifier> | <StringLiteral> | <CastToString> | <ScalarAttribute>

<StringNonFieldOperand> ::=
    <StringLiteral> | <CastToString> | <ScalarAttribute>

<ClaimPathStringOperand> ::= <StringNonFieldOperand>

<NumericalOperand> ::=
    <NumericalLiteral> | <CastToNumerical> | <DateTimeToNum>

<HexOperand> ::=
    <HexLiteral> | <CastToHex>

<BoolOperand> ::=
    <BoolLiteral> | <CastToBool>

<DateTimeOperand> ::=
    <DateTimeLiteral> | <CastToDateTime> | <DateTimeGlobalAttribute>

<TimeOperand> ::=
    <TimeLiteral> | <CastToTime>

<CastOperand> ::= <Operand> | <ClaimPathAttribute>

<StringCastOperand> ::= <StringOperand> | <ClaimPathAttribute>

<CastToString> ::=
    "str" <Ws> "(" <Ws> <CastOperand> <Ws> ")" <Ws>

<CastToNumerical> ::=
    "num" <Ws> "(" <Ws> <CastOperand> <Ws> ")" <Ws>

<CastToHex> ::=
    "hex" <Ws> "(" <Ws> <CastOperand> <Ws> ")" <Ws>

<CastToBool> ::=
    "bool" <Ws> "(" <Ws> <CastOperand> <Ws> ")" <Ws>

<CastToDateTime> ::=
    "dateTime" <Ws> "(" <Ws> <StringCastOperand> <Ws> ")" <Ws>

<CastToTime> ::=
    "time" <Ws> "(" <Ws> ( <StringCastOperand> | <DateTimeOperand> ) <Ws> ")" <Ws>
