<UseFormula> ::=
    "USEFORMULA" <Ws> <StringLiteral> <Ws>

<logicalExpression> ::= <logicalNestedExpression> | <logicalOrExpression> | <logicalAndExpression> |
<logicalNotExpression> | <matchExpression> | <BoolLiteral> | <castToBool> | <singleComparison>
<logicalNestedExpression> ::= "(" <Ws> <logicalExpression> ")" <Ws>
<logicalOrExpression> ::= "$or" <Ws> "(" <Ws> <logicalExpression> ( "," <Ws> <logicalExpression> )+ ")" <Ws>
<logicalAndExpression> ::= "$and" <Ws> "(" <Ws> <logicalExpression> ( "," <Ws> <logicalExpression> )+ ")" <Ws>
<logicalNotExpression> ::= "$not" <Ws> "(" <Ws> <logicalExpression> ")" <Ws>

<matchExpression> ::= ( "$match" <Ws> "(" <Ws> ( <singleComparison> | <matchExpression> ) ( "," <Ws> ( <singleComparison> | <matchExpression> ) )* ")" <Ws> )

<singleComparison> ::=
    <stringComparison> |
    <numericalComparison> |
    <hexComparison> |
    <boolComparison> |
    <dateTimeComparison> |
    <timeComparison>

<allComparisons> ::= ( "$eq" | "$ne" | "$gt" | "$lt" | "$ge" | "$le" )

<stringComparison> ::=
    ( ( "$starts-with" | "$ends-with" | "$contains" | "$regex") <Ws> "(" <Ws> <stringOperand> <Ws> "," <Ws> <stringOperand> <Ws> ")" <Ws> ) |
    ( <stringOperand> <Ws> <allComparisons> <Ws> <stringNonFieldOperand> <Ws> ) |
    ( <stringNonFieldOperand> <Ws> <allComparisons> <Ws> <stringOperand> <Ws> )

<numericalComparison> ::=
    ( <numericalOperand> <Ws> <allComparisons> <Ws> <numericalOperand> <Ws> ) |
    ( <numericalOperand> <Ws> <allComparisons> <Ws> <FieldIdentifier> <Ws> ) |
    ( <FieldIdentifier> <Ws> <allComparisons> <Ws> <numericalOperand> <Ws> )

<hexComparison> ::=
    ( <hexOperand> <Ws> <allComparisons> <Ws> <hexOperand> <Ws> ) |
    ( <hexOperand> <Ws> <allComparisons> <Ws> <FieldIdentifier> <Ws> ) |
    ( <FieldIdentifier> <Ws> <allComparisons> <Ws> <hexOperand> <Ws> )

<boolComparison> ::=
    ( <boolOperand> <Ws> ( "$eq" | "$ne" ) <Ws> <boolOperand> <Ws> ) |
    ( <boolOperand> <Ws> ( "$eq" | "$ne" ) <Ws> <FieldIdentifier> <Ws> ) |
    ( <FieldIdentifier> <Ws> ( "$eq" | "$ne" ) <Ws> <boolOperand> <Ws> )

<dateTimeComparison> ::=
    ( <dateTimeOperand> <Ws> <allComparisons> <Ws> <dateTimeOperand> <Ws> ) |
    ( <dateTimeOperand> <Ws> <allComparisons> <Ws> <FieldIdentifier> <Ws> ) |
    ( <FieldIdentifier> <Ws> <allComparisons> <Ws> <dateTimeOperand> <Ws> )

<dateTimeToNum> ::=
    ( "$dayOfWeek" | "$dayOfMonth" | "$month" | "$year" ) <Ws> "(" <Ws> <dateTimeOperand> <Ws> ")" <Ws>

<timeComparison> ::=
    ( <timeOperand> <Ws> <allComparisons> <Ws> <timeOperand> <Ws> ) |
    ( <timeOperand> <Ws> <allComparisons> <Ws> <FieldIdentifier> <Ws> ) |
    ( <FieldIdentifier> <Ws> <allComparisons> <Ws> <timeOperand> <Ws> )

<operand> ::= <stringOperand> | <numericalOperand> | <hexOperand> | <boolOperand> | <dateTimeOperand> | <timeOperand>

<stringOperand> ::=
    <FieldIdentifier> | <StringLiteral> | <castToString> | <SingleAttribute>

<stringNonFieldOperand> ::=
    <StringLiteral> | <castToString> | <SingleAttribute>

<numericalOperand> ::=
    <NumericalLiteral> | <castToNumerical> | <dateTimeToNum>

<hexOperand> ::=
    <HexLiteral> | <castToHex>

<boolOperand> ::=
    <BoolLiteral> | <castToBool>

<dateTimeOperand> ::=
    <DateTimeLiteral> | <castToDateTime> | <DateTimeGlobalAttribute>

<timeOperand> ::=
    <TimeLiteral> | <castToTime>

<castToString> ::=
    "str" <Ws> "(" <Ws> <operand> <Ws> ")" <Ws>

<castToNumerical> ::=
    "num" <Ws> "(" <Ws> <operand> <Ws> ")" <Ws>

<castToHex> ::=
    "hex" <Ws> "(" <Ws> <operand> <Ws> ")" <Ws>

<castToBool> ::=
    "bool" <Ws> "(" <Ws> <operand> <Ws> ")" <Ws>

<castToDateTime> ::=
    "dateTime" <Ws> "(" <Ws> <stringOperand> <Ws> ")" <Ws>

<castToTime> ::=
    "time" <Ws> "(" <Ws> ( <stringOperand> | <dateTimeOperand> ) <Ws> ")" <Ws>
