<UseFormula> ::=
    "USEFORMULAS" <ws> <StringLiteral> <ws>

<Condition> ::= <logicalExpression> <ws>

<logicalExpression> ::= <logicalNestedExpression> | <logicalOrExpression> | <logicalAndExpression> |
<logicalNotExpression> | <matchExpression> | <BoolLiteral> | <castToBool> | <singleComparison>
<logicalNestedExpression> ::= "(" <ws> <logicalExpression> ")" <ws>
<logicalOrExpression> ::= "$or" <ws> "(" <ws> <logicalExpression> ( "," <ws> <logicalExpression> )+ ")" <ws>
<logicalAndExpression> ::= "$and" <ws> "(" <ws> <logicalExpression> ( "," <ws> <logicalExpression> )+ ")" <ws>
<logicalNotExpression> ::= "$not" <ws> "(" <ws> <logicalExpression> ")" <ws>

<matchExpression> ::= ( "$match" <ws> "(" <ws> ( <singleComparison> | <matchExpression> ) ( "," <ws> ( <singleComparison> | <matchExpression> ) )* ")" <ws> )

<singleComparison> ::=
    <stringComparison> |
    <numericalComparison> |
    <hexComparison> |
    <boolComparison> |
    <dateTimeComparison> |
    <timeComparison>

<allComparisons> ::= ( "$eq" | "$ne" | "$gt" | "$lt" | "$ge" | "$le" )

<stringComparison> ::=
    ( ( "$starts-with" | "ends-with" | "$contains" | "$regex") <ws> "(" <ws> <stringOperand> <ws> "," <ws> <stringOperand> <ws> ")" <ws> ) |
    ( <stringOperand> <ws> <allComparisons> <ws> <stringOperand> <ws> ) |
    ( <stringOperand> <ws> <allComparisons> <ws> <FieldIdentifierString> <ws> ) |
    ( <FieldIdentifierString> <ws> <allComparisons> <ws> <stringOperand> <ws> )

<numericalComparison> ::=
    ( <numericalOperand> <ws> <allComparisons> <ws> <numericalOperand> <ws> ) |
    ( <numericalOperand> <ws> <allComparisons> <ws> <FieldIdentifierString> <ws> ) |
    ( <FieldIdentifierString> <ws> <allComparisons> <ws> <numericalOperand> <ws> )

<hexComparison> ::=
    <hexOperand> <ws> <allComparisons> <ws> <hexOperand> <ws>

<boolComparison> ::=
    <boolOperand> <ws> ( "$eq" | "$ne" ) <ws> <boolOperand> <ws>

<dateTimeComparison> ::=
    <dateTimeOperand> <ws> <allComparisons> <ws> <dateTimeOperand> <ws>

<dateTimeToNum> ::=
    ( "$dayOfWeek" | "$dayOfMonth" | "$month" | "$year" ) <ws> "(" <ws> <dateTimeOperand> <ws> ")" <ws>

<timeComparison> ::=
    <timeOperand> <ws> <allComparisons> <ws> <timeOperand> <ws>

<operand> ::= <stringOperand> | <numericalOperand> | <hexOperand> | <boolOperand> | <dateTimeOperand> | <timeOperand>

<stringOperand> ::=
    <FieldIdentifierString> | <StringLiteral> | <castToString> | <SingleAttribute>

<numericalOperand> ::=
    <NumericalLiteral> | <castToNumerical> | <dateTimeToNum>

<hexOperand> ::=
    <HexLiteral> | <castToHex>

<boolOperand> ::=
    <BoolLiteral> | <castToBool>

<dateTimeOperand> ::=
    <DateTimeLiteral> | <castToDateTime> | <GlobalAttribute>

<timeOperand> ::=
    <TimeLiteral> | <castToTime>

<castToString> ::=
    "str" <ws> "(" <ws> <operand> <ws> ")" <ws>

<castToNumerical> ::=
    "num" <ws> "(" <ws> <operand> <ws> ")" <ws>

<castToHex> ::=
    "hex" <ws> "(" <ws> <operand> <ws> ")" <ws>

<castToBool> ::=
    "bool" <ws> "(" <ws> <operand> <ws> ")" <ws>

<castToDateTime> ::=
    "dateTime" <ws> "(" <ws> <stringOperand> <ws> ")" <ws>

<castToTime> ::=
    "time" <ws> "(" <ws> ( <stringOperand> | <dateTimeOperand> ) <ws> ")" <ws>
