<SingleObject> ::=
    <RouteObject> | <IdentifiableObject> | <ReferableObject> | <FragmentObject> | <DescriptorObject>

<RouteObject> ::=
    "ROUTE" <ws> <RouteLiteral> <ws>

<IdentifierInstance> ::= "(" <StringLiteral> ")"
<IdentifierInstanceOrAll> ::= <IdentifierInstance> | "(\"*\")"

<IdentifiableObject> ::=
    "IDENTIFIABLE" <ws> ("$aas" | "$sm" | "$cd") <IdentifierInstanceOrAll>

<ReferableObject> ::=
    "REFERABLE" <ws> "$sme" <IdentifierInstanceOrAll> "." <idShortPath>

<FragmentObject> ::=
    "FRAGMENT" <ws> "$sme" <IdentifierInstanceOrAll> "." <idShortPath> ( <ws> <StringLiteral> )+
 
<DescriptorObject> ::=
    "DESCRIPTOR" <ws> ("$aasdesc" | "$smdesc") <IdentifierInstanceOrAll>

<ObjectGroup> ::=
    ( <SingleObject> <ws> )*
    | ( <UseObjectGroup> <ws> )*

<UseObjectGroup> ::=
    "USEOBJECTS" <ws> <StringLiteral> <ws>
