<SingleObject> ::=
    <RouteObject> | <IdentifiableObject> | <ReferableObject> | <FragmentObject> | <DescriptorObject>

<RouteObject> ::=
    "ROUTE" <Ws> <RouteLiteral> <Ws>

<IdentifierInstance> ::= "(" <StringLiteral> ")"
<IdentifierInstanceOrAll> ::= <IdentifierInstance> | "(\"*\")"

<IdentifiableObject> ::=
    "IDENTIFIABLE" <Ws> ("$aas" | "$sm" | "$cd") <IdentifierInstanceOrAll>

<ReferableObject> ::=
    "REFERABLE" <Ws> "$sme" <IdentifierInstanceOrAll> "." <IdShortPath>

<FragmentObject> ::=
    "FRAGMENT" <Ws> <FragmentLiteral> <Ws>

<DescriptorObject> ::=
    "DESCRIPTOR" <Ws> ("$aasdesc" | "$smdesc") <IdentifierInstanceOrAll>

<ObjectGroup> ::=
    ( <SingleObject> <Ws> )*
    | ( <UseObjectGroup> <Ws> )*

<UseObjectGroup> ::=
    "USEOBJECTS" <Ws> <StringLiteral> <Ws>
